import type { RawWord } from "../parse-hsk-data";

export const hsk1Words: RawWord[] = [
  { hanzi: "爱", pinyin: "ài", english: "to love; love", pos: "v/n", frequency: 1 },
  { hanzi: "八", pinyin: "bā", english: "eight", pos: "num", frequency: 2 },
  { hanzi: "爸爸", pinyin: "bàba", english: "dad; father", pos: "n", frequency: 3 },
  { hanzi: "杯子", pinyin: "bēizi", english: "cup; glass", pos: "n", frequency: 4 },
  { hanzi: "北京", pinyin: "Běijīng", english: "Beijing", pos: "n", frequency: 5 },
  { hanzi: "本", pinyin: "běn", english: "volume; (measure word for books)", pos: "m", frequency: 6 },
  { hanzi: "不客气", pinyin: "bù kèqi", english: "you're welcome", pos: "expr", frequency: 7 },
  { hanzi: "不", pinyin: "bù", english: "no; not", pos: "adv", frequency: 8 },
  { hanzi: "菜", pinyin: "cài", english: "dish; food; vegetable", pos: "n", frequency: 9 },
  { hanzi: "茶", pinyin: "chá", english: "tea", pos: "n", frequency: 10 },
  { hanzi: "吃", pinyin: "chī", english: "to eat", pos: "v", frequency: 11 },
  { hanzi: "出租车", pinyin: "chūzūchē", english: "taxi", pos: "n", frequency: 12 },
  { hanzi: "打电话", pinyin: "dǎ diànhuà", english: "to make a phone call", pos: "v", frequency: 13 },
  { hanzi: "大", pinyin: "dà", english: "big; large", pos: "adj", frequency: 14 },
  { hanzi: "的", pinyin: "de", english: "structural particle", pos: "part", frequency: 15 },
  { hanzi: "点", pinyin: "diǎn", english: "o'clock; point; dot", pos: "m/n", frequency: 16 },
  { hanzi: "电脑", pinyin: "diànnǎo", english: "computer", pos: "n", frequency: 17 },
  { hanzi: "电视", pinyin: "diànshì", english: "television", pos: "n", frequency: 18 },
  { hanzi: "电影", pinyin: "diànyǐng", english: "movie; film", pos: "n", frequency: 19 },
  { hanzi: "东西", pinyin: "dōngxi", english: "thing; stuff", pos: "n", frequency: 20 },
  { hanzi: "都", pinyin: "dōu", english: "all; both", pos: "adv", frequency: 21 },
  { hanzi: "读", pinyin: "dú", english: "to read aloud; to study", pos: "v", frequency: 22 },
  { hanzi: "对不起", pinyin: "duìbuqǐ", english: "sorry; excuse me", pos: "expr", frequency: 23 },
  { hanzi: "多", pinyin: "duō", english: "many; much; more", pos: "adj", frequency: 24 },
  { hanzi: "多少", pinyin: "duōshao", english: "how many; how much", pos: "pron", frequency: 25 },
  { hanzi: "儿子", pinyin: "érzi", english: "son", pos: "n", frequency: 26 },
  { hanzi: "二", pinyin: "èr", english: "two", pos: "num", frequency: 27 },
  { hanzi: "饭店", pinyin: "fàndiàn", english: "hotel; restaurant", pos: "n", frequency: 28 },
  { hanzi: "飞机", pinyin: "fēijī", english: "airplane", pos: "n", frequency: 29 },
  { hanzi: "分钟", pinyin: "fēnzhōng", english: "minute", pos: "m", frequency: 30 },
  { hanzi: "高兴", pinyin: "gāoxìng", english: "happy; glad", pos: "adj", frequency: 31 },
  { hanzi: "个", pinyin: "gè", english: "(general measure word)", pos: "m", frequency: 32 },
  { hanzi: "工作", pinyin: "gōngzuò", english: "work; job; to work", pos: "n/v", frequency: 33 },
  { hanzi: "狗", pinyin: "gǒu", english: "dog", pos: "n", frequency: 34 },
  { hanzi: "汉语", pinyin: "Hànyǔ", english: "Chinese (language)", pos: "n", frequency: 35 },
  { hanzi: "好", pinyin: "hǎo", english: "good; well", pos: "adj", frequency: 36 },
  { hanzi: "号", pinyin: "hào", english: "number; date", pos: "m/n", frequency: 37 },
  { hanzi: "喝", pinyin: "hē", english: "to drink", pos: "v", frequency: 38 },
  { hanzi: "和", pinyin: "hé", english: "and; with", pos: "conj", frequency: 39 },
  { hanzi: "很", pinyin: "hěn", english: "very", pos: "adv", frequency: 40 },
  { hanzi: "后面", pinyin: "hòumiàn", english: "behind; in the back", pos: "n", frequency: 41 },
  { hanzi: "回", pinyin: "huí", english: "to return; to go back", pos: "v", frequency: 42 },
  { hanzi: "会", pinyin: "huì", english: "can; to be able to", pos: "v/aux", frequency: 43 },
  { hanzi: "几", pinyin: "jǐ", english: "how many; several", pos: "pron/num", frequency: 44 },
  { hanzi: "家", pinyin: "jiā", english: "home; family; house", pos: "n", frequency: 45 },
  { hanzi: "叫", pinyin: "jiào", english: "to be called; to call", pos: "v", frequency: 46 },
  { hanzi: "今天", pinyin: "jīntiān", english: "today", pos: "n", frequency: 47 },
  { hanzi: "九", pinyin: "jiǔ", english: "nine", pos: "num", frequency: 48 },
  { hanzi: "开", pinyin: "kāi", english: "to open; to drive", pos: "v", frequency: 49 },
  { hanzi: "看", pinyin: "kàn", english: "to look; to watch; to read", pos: "v", frequency: 50 },
  { hanzi: "看见", pinyin: "kànjiàn", english: "to see; to catch sight of", pos: "v", frequency: 51 },
  { hanzi: "块", pinyin: "kuài", english: "yuan (currency); piece", pos: "m", frequency: 52 },
  { hanzi: "来", pinyin: "lái", english: "to come", pos: "v", frequency: 53 },
  { hanzi: "老师", pinyin: "lǎoshī", english: "teacher", pos: "n", frequency: 54 },
  { hanzi: "了", pinyin: "le", english: "particle (completed action)", pos: "part", frequency: 55 },
  { hanzi: "冷", pinyin: "lěng", english: "cold", pos: "adj", frequency: 56 },
  { hanzi: "里", pinyin: "lǐ", english: "inside; in", pos: "n", frequency: 57 },
  { hanzi: "六", pinyin: "liù", english: "six", pos: "num", frequency: 58 },
  { hanzi: "妈妈", pinyin: "māma", english: "mom; mother", pos: "n", frequency: 59 },
  { hanzi: "吗", pinyin: "ma", english: "question particle", pos: "part", frequency: 60 },
  { hanzi: "买", pinyin: "mǎi", english: "to buy", pos: "v", frequency: 61 },
  { hanzi: "猫", pinyin: "māo", english: "cat", pos: "n", frequency: 62 },
  { hanzi: "没关系", pinyin: "méi guānxi", english: "it doesn't matter; never mind", pos: "expr", frequency: 63 },
  { hanzi: "没有", pinyin: "méiyǒu", english: "do not have; there is not", pos: "v", frequency: 64 },
  { hanzi: "米饭", pinyin: "mǐfàn", english: "cooked rice", pos: "n", frequency: 65 },
  { hanzi: "明天", pinyin: "míngtiān", english: "tomorrow", pos: "n", frequency: 66 },
  { hanzi: "名字", pinyin: "míngzi", english: "name", pos: "n", frequency: 67 },
  { hanzi: "哪", pinyin: "nǎ", english: "which", pos: "pron", frequency: 68 },
  { hanzi: "哪儿", pinyin: "nǎr", english: "where", pos: "pron", frequency: 69 },
  { hanzi: "那", pinyin: "nà", english: "that", pos: "pron", frequency: 70 },
  { hanzi: "呢", pinyin: "ne", english: "question particle (and you?)", pos: "part", frequency: 71 },
  { hanzi: "能", pinyin: "néng", english: "can; to be able to", pos: "aux", frequency: 72 },
  { hanzi: "你", pinyin: "nǐ", english: "you", pos: "pron", frequency: 73 },
  { hanzi: "你好", pinyin: "nǐ hǎo", english: "hello; hi", pos: "expr", frequency: 74 },
  { hanzi: "年", pinyin: "nián", english: "year", pos: "m/n", frequency: 75 },
  { hanzi: "女儿", pinyin: "nǚér", english: "daughter", pos: "n", frequency: 76 },
  { hanzi: "朋友", pinyin: "péngyou", english: "friend", pos: "n", frequency: 77 },
  { hanzi: "漂亮", pinyin: "piàoliang", english: "pretty; beautiful", pos: "adj", frequency: 78 },
  { hanzi: "苹果", pinyin: "píngguǒ", english: "apple", pos: "n", frequency: 79 },
  { hanzi: "七", pinyin: "qī", english: "seven", pos: "num", frequency: 80 },
  { hanzi: "钱", pinyin: "qián", english: "money", pos: "n", frequency: 81 },
  { hanzi: "前面", pinyin: "qiánmiàn", english: "in front; ahead", pos: "n", frequency: 82 },
  { hanzi: "请", pinyin: "qǐng", english: "please; to invite", pos: "v/adv", frequency: 83 },
  { hanzi: "去", pinyin: "qù", english: "to go", pos: "v", frequency: 84 },
  { hanzi: "热", pinyin: "rè", english: "hot", pos: "adj", frequency: 85 },
  { hanzi: "人", pinyin: "rén", english: "person; people", pos: "n", frequency: 86 },
  { hanzi: "认识", pinyin: "rènshi", english: "to know; to recognize", pos: "v", frequency: 87 },
  { hanzi: "日", pinyin: "rì", english: "day; sun", pos: "n/m", frequency: 88 },
  { hanzi: "三", pinyin: "sān", english: "three", pos: "num", frequency: 89 },
  { hanzi: "商店", pinyin: "shāngdiàn", english: "shop; store", pos: "n", frequency: 90 },
  { hanzi: "上", pinyin: "shàng", english: "up; above; on top", pos: "n/v", frequency: 91 },
  { hanzi: "上午", pinyin: "shàngwǔ", english: "morning; before noon", pos: "n", frequency: 92 },
  { hanzi: "少", pinyin: "shǎo", english: "few; little; less", pos: "adj", frequency: 93 },
  { hanzi: "谁", pinyin: "shéi", english: "who; whom", pos: "pron", frequency: 94 },
  { hanzi: "什么", pinyin: "shénme", english: "what", pos: "pron", frequency: 95 },
  { hanzi: "十", pinyin: "shí", english: "ten", pos: "num", frequency: 96 },
  { hanzi: "时候", pinyin: "shíhou", english: "time; moment; when", pos: "n", frequency: 97 },
  { hanzi: "是", pinyin: "shì", english: "to be; yes", pos: "v", frequency: 98 },
  { hanzi: "书", pinyin: "shū", english: "book", pos: "n", frequency: 99 },
  { hanzi: "水", pinyin: "shuǐ", english: "water", pos: "n", frequency: 100 },
  { hanzi: "水果", pinyin: "shuǐguǒ", english: "fruit", pos: "n", frequency: 101 },
  { hanzi: "睡觉", pinyin: "shuìjiào", english: "to sleep", pos: "v", frequency: 102 },
  { hanzi: "说", pinyin: "shuō", english: "to speak; to say", pos: "v", frequency: 103 },
  { hanzi: "四", pinyin: "sì", english: "four", pos: "num", frequency: 104 },
  { hanzi: "岁", pinyin: "suì", english: "years old; age", pos: "m", frequency: 105 },
  { hanzi: "他", pinyin: "tā", english: "he; him", pos: "pron", frequency: 106 },
  { hanzi: "她", pinyin: "tā", english: "she; her", pos: "pron", frequency: 107 },
  { hanzi: "太", pinyin: "tài", english: "too; extremely", pos: "adv", frequency: 108 },
  { hanzi: "天气", pinyin: "tiānqì", english: "weather", pos: "n", frequency: 109 },
  { hanzi: "听", pinyin: "tīng", english: "to listen; to hear", pos: "v", frequency: 110 },
  { hanzi: "同学", pinyin: "tóngxué", english: "classmate", pos: "n", frequency: 111 },
  { hanzi: "喂", pinyin: "wèi", english: "hello (on phone); hey", pos: "interj", frequency: 112 },
  { hanzi: "我", pinyin: "wǒ", english: "I; me", pos: "pron", frequency: 113 },
  { hanzi: "我们", pinyin: "wǒmen", english: "we; us", pos: "pron", frequency: 114 },
  { hanzi: "五", pinyin: "wǔ", english: "five", pos: "num", frequency: 115 },
  { hanzi: "下", pinyin: "xià", english: "down; below; next", pos: "n/v", frequency: 116 },
  { hanzi: "下午", pinyin: "xiàwǔ", english: "afternoon", pos: "n", frequency: 117 },
  { hanzi: "下雨", pinyin: "xià yǔ", english: "to rain", pos: "v", frequency: 118 },
  { hanzi: "先生", pinyin: "xiānsheng", english: "Mr.; sir; husband", pos: "n", frequency: 119 },
  { hanzi: "现在", pinyin: "xiànzài", english: "now; at present", pos: "n", frequency: 120 },
  { hanzi: "想", pinyin: "xiǎng", english: "to think; to want; to miss", pos: "v", frequency: 121 },
  { hanzi: "小", pinyin: "xiǎo", english: "small; little; young", pos: "adj", frequency: 122 },
  { hanzi: "小姐", pinyin: "xiǎojiě", english: "Miss; young lady", pos: "n", frequency: 123 },
  { hanzi: "些", pinyin: "xiē", english: "some; a few", pos: "m", frequency: 124 },
  { hanzi: "写", pinyin: "xiě", english: "to write", pos: "v", frequency: 125 },
  { hanzi: "谢谢", pinyin: "xièxie", english: "thank you", pos: "expr", frequency: 126 },
  { hanzi: "星期", pinyin: "xīngqī", english: "week", pos: "n", frequency: 127 },
  { hanzi: "学生", pinyin: "xuésheng", english: "student", pos: "n", frequency: 128 },
  { hanzi: "学习", pinyin: "xuéxí", english: "to study; to learn", pos: "v", frequency: 129 },
  { hanzi: "学校", pinyin: "xuéxiào", english: "school", pos: "n", frequency: 130 },
  { hanzi: "一", pinyin: "yī", english: "one", pos: "num", frequency: 131 },
  { hanzi: "一点儿", pinyin: "yīdiǎnr", english: "a little bit", pos: "expr", frequency: 132 },
  { hanzi: "衣服", pinyin: "yīfu", english: "clothes", pos: "n", frequency: 133 },
  { hanzi: "医生", pinyin: "yīshēng", english: "doctor; physician", pos: "n", frequency: 134 },
  { hanzi: "医院", pinyin: "yīyuàn", english: "hospital", pos: "n", frequency: 135 },
  { hanzi: "椅子", pinyin: "yǐzi", english: "chair", pos: "n", frequency: 136 },
  { hanzi: "有", pinyin: "yǒu", english: "to have; there is/are", pos: "v", frequency: 137 },
  { hanzi: "月", pinyin: "yuè", english: "month; moon", pos: "n/m", frequency: 138 },
  { hanzi: "再见", pinyin: "zàijiàn", english: "goodbye", pos: "expr", frequency: 139 },
  { hanzi: "在", pinyin: "zài", english: "at; in; on; to be present", pos: "prep/v", frequency: 140 },
  { hanzi: "怎么", pinyin: "zěnme", english: "how; why", pos: "pron", frequency: 141 },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", english: "how about; how is it", pos: "pron", frequency: 142 },
  { hanzi: "这", pinyin: "zhè", english: "this", pos: "pron", frequency: 143 },
  { hanzi: "中国", pinyin: "Zhōngguó", english: "China", pos: "n", frequency: 144 },
  { hanzi: "中午", pinyin: "zhōngwǔ", english: "noon; midday", pos: "n", frequency: 145 },
  { hanzi: "住", pinyin: "zhù", english: "to live; to reside", pos: "v", frequency: 146 },
  { hanzi: "桌子", pinyin: "zhuōzi", english: "table; desk", pos: "n", frequency: 147 },
  { hanzi: "字", pinyin: "zì", english: "character; word", pos: "n", frequency: 148 },
  { hanzi: "昨天", pinyin: "zuótiān", english: "yesterday", pos: "n", frequency: 149 },
  { hanzi: "坐", pinyin: "zuò", english: "to sit; to travel by", pos: "v", frequency: 150 },
];
