import type { RawWord } from "../parse-hsk-data";

export const hsk2Words: RawWord[] = [
  { hanzi: "吧", pinyin: "ba", english: "particle (suggestion/assumption)", pos: "part", frequency: 1 },
  { hanzi: "白", pinyin: "bái", english: "white", pos: "adj", frequency: 2 },
  { hanzi: "百", pinyin: "bǎi", english: "hundred", pos: "num", frequency: 3 },
  { hanzi: "帮助", pinyin: "bāngzhù", english: "to help; help", pos: "v/n", frequency: 4 },
  { hanzi: "报纸", pinyin: "bàozhǐ", english: "newspaper", pos: "n", frequency: 5 },
  { hanzi: "比", pinyin: "bǐ", english: "to compare; than", pos: "prep/v", frequency: 6 },
  { hanzi: "别", pinyin: "bié", english: "don't; other", pos: "adv/adj", frequency: 7 },
  { hanzi: "宾馆", pinyin: "bīnguǎn", english: "hotel; guesthouse", pos: "n", frequency: 8 },
  { hanzi: "长", pinyin: "cháng", english: "long", pos: "adj", frequency: 9 },
  { hanzi: "唱歌", pinyin: "chànggē", english: "to sing (a song)", pos: "v", frequency: 10 },
  { hanzi: "出", pinyin: "chū", english: "to go out; to exit", pos: "v", frequency: 11 },
  { hanzi: "穿", pinyin: "chuān", english: "to wear; to put on", pos: "v", frequency: 12 },
  { hanzi: "次", pinyin: "cì", english: "time; occurrence (measure word)", pos: "m", frequency: 13 },
  { hanzi: "从", pinyin: "cóng", english: "from; since", pos: "prep", frequency: 14 },
  { hanzi: "错", pinyin: "cuò", english: "wrong; mistake", pos: "adj/n", frequency: 15 },
  { hanzi: "打篮球", pinyin: "dǎ lánqiú", english: "to play basketball", pos: "v", frequency: 16 },
  { hanzi: "大家", pinyin: "dàjiā", english: "everyone; everybody", pos: "pron", frequency: 17 },
  { hanzi: "到", pinyin: "dào", english: "to arrive; to reach", pos: "v/prep", frequency: 18 },
  { hanzi: "地方", pinyin: "dìfang", english: "place; area", pos: "n", frequency: 19 },
  { hanzi: "弟弟", pinyin: "dìdi", english: "younger brother", pos: "n", frequency: 20 },
  { hanzi: "第一", pinyin: "dì yī", english: "first; number one", pos: "num", frequency: 21 },
  { hanzi: "懂", pinyin: "dǒng", english: "to understand; to know", pos: "v", frequency: 22 },
  { hanzi: "对", pinyin: "duì", english: "correct; right; toward", pos: "adj/prep", frequency: 23 },
  { hanzi: "房间", pinyin: "fángjiān", english: "room", pos: "n", frequency: 24 },
  { hanzi: "非常", pinyin: "fēicháng", english: "very; extremely; unusual", pos: "adv", frequency: 25 },
  { hanzi: "服务员", pinyin: "fúwùyuán", english: "waiter; service staff", pos: "n", frequency: 26 },
  { hanzi: "高", pinyin: "gāo", english: "tall; high", pos: "adj", frequency: 27 },
  { hanzi: "告诉", pinyin: "gàosu", english: "to tell; to inform", pos: "v", frequency: 28 },
  { hanzi: "哥哥", pinyin: "gēge", english: "older brother", pos: "n", frequency: 29 },
  { hanzi: "给", pinyin: "gěi", english: "to give; for", pos: "v/prep", frequency: 30 },
  { hanzi: "公共汽车", pinyin: "gōnggòng qìchē", english: "bus", pos: "n", frequency: 31 },
  { hanzi: "公司", pinyin: "gōngsī", english: "company; firm", pos: "n", frequency: 32 },
  { hanzi: "贵", pinyin: "guì", english: "expensive; honorable", pos: "adj", frequency: 33 },
  { hanzi: "过", pinyin: "guò", english: "to pass; (experiential aspect particle)", pos: "v/part", frequency: 34 },
  { hanzi: "还", pinyin: "hái", english: "still; also; in addition", pos: "adv", frequency: 35 },
  { hanzi: "孩子", pinyin: "háizi", english: "child; children", pos: "n", frequency: 36 },
  { hanzi: "好吃", pinyin: "hǎochī", english: "delicious; tasty", pos: "adj", frequency: 37 },
  { hanzi: "黑", pinyin: "hēi", english: "black; dark", pos: "adj", frequency: 38 },
  { hanzi: "红", pinyin: "hóng", english: "red", pos: "adj", frequency: 39 },
  { hanzi: "火车站", pinyin: "huǒchē zhàn", english: "train station", pos: "n", frequency: 40 },
  { hanzi: "机场", pinyin: "jīchǎng", english: "airport", pos: "n", frequency: 41 },
  { hanzi: "鸡蛋", pinyin: "jīdàn", english: "egg", pos: "n", frequency: 42 },
  { hanzi: "件", pinyin: "jiàn", english: "(measure word for clothes/matters)", pos: "m", frequency: 43 },
  { hanzi: "教室", pinyin: "jiàoshì", english: "classroom", pos: "n", frequency: 44 },
  { hanzi: "姐姐", pinyin: "jiějie", english: "older sister", pos: "n", frequency: 45 },
  { hanzi: "介绍", pinyin: "jièshào", english: "to introduce; introduction", pos: "v/n", frequency: 46 },
  { hanzi: "进", pinyin: "jìn", english: "to enter; to come in", pos: "v", frequency: 47 },
  { hanzi: "近", pinyin: "jìn", english: "near; close", pos: "adj", frequency: 48 },
  { hanzi: "就", pinyin: "jiù", english: "just; right away; then", pos: "adv", frequency: 49 },
  { hanzi: "觉得", pinyin: "juéde", english: "to feel; to think", pos: "v", frequency: 50 },
  { hanzi: "咖啡", pinyin: "kāfēi", english: "coffee", pos: "n", frequency: 51 },
  { hanzi: "开始", pinyin: "kāishǐ", english: "to begin; to start; beginning", pos: "v/n", frequency: 52 },
  { hanzi: "考试", pinyin: "kǎoshì", english: "exam; to take an exam", pos: "n/v", frequency: 53 },
  { hanzi: "可能", pinyin: "kěnéng", english: "maybe; possible; possibly", pos: "adv/adj", frequency: 54 },
  { hanzi: "可以", pinyin: "kěyǐ", english: "can; may; okay", pos: "aux", frequency: 55 },
  { hanzi: "课", pinyin: "kè", english: "class; lesson; course", pos: "n", frequency: 56 },
  { hanzi: "快", pinyin: "kuài", english: "fast; quick; soon", pos: "adj/adv", frequency: 57 },
  { hanzi: "快乐", pinyin: "kuàilè", english: "happy; joyful", pos: "adj", frequency: 58 },
  { hanzi: "累", pinyin: "lèi", english: "tired; exhausted", pos: "adj", frequency: 59 },
  { hanzi: "离", pinyin: "lí", english: "from; away from", pos: "prep", frequency: 60 },
  { hanzi: "两", pinyin: "liǎng", english: "two; both", pos: "num", frequency: 61 },
  { hanzi: "零", pinyin: "líng", english: "zero", pos: "num", frequency: 62 },
  { hanzi: "路", pinyin: "lù", english: "road; path; route", pos: "n", frequency: 63 },
  { hanzi: "旅游", pinyin: "lǚyóu", english: "to travel; tourism", pos: "v/n", frequency: 64 },
  { hanzi: "卖", pinyin: "mài", english: "to sell", pos: "v", frequency: 65 },
  { hanzi: "慢", pinyin: "màn", english: "slow", pos: "adj", frequency: 66 },
  { hanzi: "忙", pinyin: "máng", english: "busy", pos: "adj", frequency: 67 },
  { hanzi: "每", pinyin: "měi", english: "every; each", pos: "det", frequency: 68 },
  { hanzi: "妹妹", pinyin: "mèimei", english: "younger sister", pos: "n", frequency: 69 },
  { hanzi: "门", pinyin: "mén", english: "door; gate", pos: "n", frequency: 70 },
  { hanzi: "面条", pinyin: "miàntiáo", english: "noodles", pos: "n", frequency: 71 },
  { hanzi: "男", pinyin: "nán", english: "male; man", pos: "n/adj", frequency: 72 },
  { hanzi: "您", pinyin: "nín", english: "you (polite form)", pos: "pron", frequency: 73 },
  { hanzi: "牛奶", pinyin: "niúnǎi", english: "milk", pos: "n", frequency: 74 },
  { hanzi: "女", pinyin: "nǚ", english: "female; woman", pos: "n/adj", frequency: 75 },
  { hanzi: "旁边", pinyin: "pángbiān", english: "beside; next to", pos: "n", frequency: 76 },
  { hanzi: "跑步", pinyin: "pǎobù", english: "to run; jogging", pos: "v/n", frequency: 77 },
  { hanzi: "便宜", pinyin: "piányí", english: "cheap; inexpensive", pos: "adj", frequency: 78 },
  { hanzi: "票", pinyin: "piào", english: "ticket", pos: "n", frequency: 79 },
  { hanzi: "妻子", pinyin: "qīzi", english: "wife", pos: "n", frequency: 80 },
  { hanzi: "起床", pinyin: "qǐchuáng", english: "to get up; to get out of bed", pos: "v", frequency: 81 },
  { hanzi: "千", pinyin: "qiān", english: "thousand", pos: "num", frequency: 82 },
  { hanzi: "晴", pinyin: "qíng", english: "sunny; clear (weather)", pos: "adj", frequency: 83 },
  { hanzi: "去年", pinyin: "qùnián", english: "last year", pos: "n", frequency: 84 },
  { hanzi: "让", pinyin: "ràng", english: "to let; to allow; to make", pos: "v", frequency: 85 },
  { hanzi: "日记", pinyin: "rìjì", english: "diary; journal", pos: "n", frequency: 86 },
  { hanzi: "如果", pinyin: "rúguǒ", english: "if; in case; in the event that", pos: "conj", frequency: 87 },
  { hanzi: "上班", pinyin: "shàngbān", english: "to go to work", pos: "v", frequency: 88 },
  { hanzi: "身体", pinyin: "shēntǐ", english: "body; health", pos: "n", frequency: 89 },
  { hanzi: "生病", pinyin: "shēngbìng", english: "to get sick; to fall ill", pos: "v", frequency: 90 },
  { hanzi: "生日", pinyin: "shēngrì", english: "birthday", pos: "n", frequency: 91 },
  { hanzi: "时间", pinyin: "shíjiān", english: "time; period", pos: "n", frequency: 92 },
  { hanzi: "事情", pinyin: "shìqing", english: "matter; thing; affair", pos: "n", frequency: 93 },
  { hanzi: "手表", pinyin: "shǒubiǎo", english: "watch; wristwatch", pos: "n", frequency: 94 },
  { hanzi: "手机", pinyin: "shǒujī", english: "mobile phone", pos: "n", frequency: 95 },
  { hanzi: "说话", pinyin: "shuōhuà", english: "to speak; to talk", pos: "v", frequency: 96 },
  { hanzi: "送", pinyin: "sòng", english: "to give (as gift); to send; to see off", pos: "v", frequency: 97 },
  { hanzi: "虽然", pinyin: "suīrán", english: "although; even though", pos: "conj", frequency: 98 },
  { hanzi: "所以", pinyin: "suǒyǐ", english: "so; therefore", pos: "conj", frequency: 99 },
  { hanzi: "它", pinyin: "tā", english: "it", pos: "pron", frequency: 100 },
  { hanzi: "踢足球", pinyin: "tī zúqiú", english: "to play football/soccer", pos: "v", frequency: 101 },
  { hanzi: "题", pinyin: "tí", english: "topic; question; problem", pos: "n", frequency: 102 },
  { hanzi: "跳舞", pinyin: "tiàowǔ", english: "to dance", pos: "v", frequency: 103 },
  { hanzi: "外", pinyin: "wài", english: "outside; foreign", pos: "n/adj", frequency: 104 },
  { hanzi: "完", pinyin: "wán", english: "to finish; to complete", pos: "v", frequency: 105 },
  { hanzi: "玩", pinyin: "wán", english: "to play; to have fun", pos: "v", frequency: 106 },
  { hanzi: "晚上", pinyin: "wǎnshang", english: "evening; night", pos: "n", frequency: 107 },
  { hanzi: "往", pinyin: "wǎng", english: "toward; to go", pos: "prep/v", frequency: 108 },
  { hanzi: "为什么", pinyin: "wèishénme", english: "why; for what reason", pos: "pron", frequency: 109 },
  { hanzi: "问", pinyin: "wèn", english: "to ask; to inquire", pos: "v", frequency: 110 },
  { hanzi: "问题", pinyin: "wèntí", english: "question; problem; issue", pos: "n", frequency: 111 },
  { hanzi: "西瓜", pinyin: "xīguā", english: "watermelon", pos: "n", frequency: 112 },
  { hanzi: "希望", pinyin: "xīwàng", english: "to hope; hope", pos: "v/n", frequency: 113 },
  { hanzi: "洗", pinyin: "xǐ", english: "to wash", pos: "v", frequency: 114 },
  { hanzi: "先", pinyin: "xiān", english: "first; before", pos: "adv", frequency: 115 },
  { hanzi: "向", pinyin: "xiàng", english: "toward; to face", pos: "prep/v", frequency: 116 },
  { hanzi: "小时", pinyin: "xiǎoshí", english: "hour", pos: "n", frequency: 117 },
  { hanzi: "笑", pinyin: "xiào", english: "to laugh; to smile", pos: "v", frequency: 118 },
  { hanzi: "新", pinyin: "xīn", english: "new", pos: "adj", frequency: 119 },
  { hanzi: "姓", pinyin: "xìng", english: "surname; to be surnamed", pos: "n/v", frequency: 120 },
  { hanzi: "休息", pinyin: "xiūxi", english: "to rest; rest", pos: "v/n", frequency: 121 },
  { hanzi: "雪", pinyin: "xuě", english: "snow", pos: "n", frequency: 122 },
  { hanzi: "颜色", pinyin: "yánsè", english: "color", pos: "n", frequency: 123 },
  { hanzi: "眼睛", pinyin: "yǎnjing", english: "eye", pos: "n", frequency: 124 },
  { hanzi: "羊肉", pinyin: "yángròu", english: "mutton; lamb", pos: "n", frequency: 125 },
  { hanzi: "药", pinyin: "yào", english: "medicine; drug", pos: "n", frequency: 126 },
  { hanzi: "要", pinyin: "yào", english: "to want; will; must", pos: "v/aux", frequency: 127 },
  { hanzi: "也", pinyin: "yě", english: "also; too", pos: "adv", frequency: 128 },
  { hanzi: "一下", pinyin: "yīxià", english: "once; a bit (softens request)", pos: "expr", frequency: 129 },
  { hanzi: "一起", pinyin: "yīqǐ", english: "together", pos: "adv", frequency: 130 },
  { hanzi: "已经", pinyin: "yǐjīng", english: "already", pos: "adv", frequency: 131 },
  { hanzi: "意思", pinyin: "yìsi", english: "meaning; idea", pos: "n", frequency: 132 },
  { hanzi: "因为", pinyin: "yīnwèi", english: "because; since", pos: "conj", frequency: 133 },
  { hanzi: "阴", pinyin: "yīn", english: "cloudy; overcast", pos: "adj", frequency: 134 },
  { hanzi: "游泳", pinyin: "yóuyǒng", english: "to swim; swimming", pos: "v/n", frequency: 135 },
  { hanzi: "右边", pinyin: "yòubiān", english: "right side", pos: "n", frequency: 136 },
  { hanzi: "鱼", pinyin: "yú", english: "fish", pos: "n", frequency: 137 },
  { hanzi: "远", pinyin: "yuǎn", english: "far; distant", pos: "adj", frequency: 138 },
  { hanzi: "运动", pinyin: "yùndòng", english: "exercise; sport; to exercise", pos: "n/v", frequency: 139 },
  { hanzi: "再", pinyin: "zài", english: "again; then; more", pos: "adv", frequency: 140 },
  { hanzi: "丈夫", pinyin: "zhàngfu", english: "husband", pos: "n", frequency: 141 },
  { hanzi: "找", pinyin: "zhǎo", english: "to look for; to seek", pos: "v", frequency: 142 },
  { hanzi: "着", pinyin: "zhe", english: "aspect particle (continuous)", pos: "part", frequency: 143 },
  { hanzi: "真", pinyin: "zhēn", english: "real; true; really", pos: "adj/adv", frequency: 144 },
  { hanzi: "正在", pinyin: "zhèngzài", english: "in the process of; currently", pos: "adv", frequency: 145 },
  { hanzi: "知道", pinyin: "zhīdào", english: "to know; to be aware of", pos: "v", frequency: 146 },
  { hanzi: "准备", pinyin: "zhǔnbèi", english: "to prepare; preparation", pos: "v/n", frequency: 147 },
  { hanzi: "走", pinyin: "zǒu", english: "to walk; to go; to leave", pos: "v", frequency: 148 },
  { hanzi: "最", pinyin: "zuì", english: "most; -est (superlative)", pos: "adv", frequency: 149 },
  { hanzi: "左边", pinyin: "zuǒbiān", english: "left side", pos: "n", frequency: 150 },
];
