import type { RawWord } from "../parse-hsk-data";

export const hsk3Words: RawWord[] = [
  { hanzi: "阿姨", pinyin: "āyí", english: "aunt; auntie (mother's sister)", pos: "n", frequency: 1 },
  { hanzi: "啊", pinyin: "a", english: "particle (exclamation/question)", pos: "part", frequency: 2 },
  { hanzi: "矮", pinyin: "ǎi", english: "short (height)", pos: "adj", frequency: 3 },
  { hanzi: "爱好", pinyin: "àihào", english: "hobby; interest", pos: "n", frequency: 4 },
  { hanzi: "安静", pinyin: "ānjìng", english: "quiet; peaceful", pos: "adj", frequency: 5 },
  { hanzi: "把", pinyin: "bǎ", english: "to hold; (disposal marker)", pos: "prep/v", frequency: 6 },
  { hanzi: "班", pinyin: "bān", english: "class; shift; (measure word for scheduled transport)", pos: "n/m", frequency: 7 },
  { hanzi: "搬", pinyin: "bān", english: "to move; to carry", pos: "v", frequency: 8 },
  { hanzi: "半", pinyin: "bàn", english: "half", pos: "num", frequency: 9 },
  { hanzi: "办法", pinyin: "bànfǎ", english: "method; way; means", pos: "n", frequency: 10 },
  { hanzi: "办公室", pinyin: "bàngōngshì", english: "office", pos: "n", frequency: 11 },
  { hanzi: "帮", pinyin: "bāng", english: "to help", pos: "v", frequency: 12 },
  { hanzi: "包", pinyin: "bāo", english: "bag; package; to wrap", pos: "n/v", frequency: 13 },
  { hanzi: "北方", pinyin: "běifāng", english: "north; northern area", pos: "n", frequency: 14 },
  { hanzi: "被", pinyin: "bèi", english: "by (passive marker)", pos: "prep", frequency: 15 },
  { hanzi: "鼻子", pinyin: "bízi", english: "nose", pos: "n", frequency: 16 },
  { hanzi: "比较", pinyin: "bǐjiào", english: "relatively; to compare", pos: "adv/v", frequency: 17 },
  { hanzi: "比赛", pinyin: "bǐsài", english: "competition; match; to compete", pos: "n/v", frequency: 18 },
  { hanzi: "必须", pinyin: "bìxū", english: "must; have to", pos: "aux", frequency: 19 },
  { hanzi: "变化", pinyin: "biànhuà", english: "change; to change", pos: "n/v", frequency: 20 },
  { hanzi: "表示", pinyin: "biǎoshì", english: "to express; to show; to indicate", pos: "v", frequency: 21 },
  { hanzi: "表演", pinyin: "biǎoyǎn", english: "to perform; performance", pos: "v/n", frequency: 22 },
  { hanzi: "别人", pinyin: "biérén", english: "other people; others", pos: "pron", frequency: 23 },
  { hanzi: "冰箱", pinyin: "bīngxiāng", english: "refrigerator", pos: "n", frequency: 24 },
  { hanzi: "不但…而且", pinyin: "bùdàn…érqiě", english: "not only…but also", pos: "conj", frequency: 25 },
  { hanzi: "菜单", pinyin: "càidān", english: "menu", pos: "n", frequency: 26 },
  { hanzi: "参加", pinyin: "cānjiā", english: "to participate; to join", pos: "v", frequency: 27 },
  { hanzi: "草", pinyin: "cǎo", english: "grass", pos: "n", frequency: 28 },
  { hanzi: "层", pinyin: "céng", english: "floor; layer (measure word)", pos: "m/n", frequency: 29 },
  { hanzi: "差", pinyin: "chà", english: "bad; poor; to lack", pos: "adj/v", frequency: 30 },
  { hanzi: "超市", pinyin: "chāoshì", english: "supermarket", pos: "n", frequency: 31 },
  { hanzi: "衬衫", pinyin: "chènshān", english: "shirt", pos: "n", frequency: 32 },
  { hanzi: "城市", pinyin: "chéngshì", english: "city; town", pos: "n", frequency: 33 },
  { hanzi: "迟到", pinyin: "chídào", english: "to be late; to arrive late", pos: "v", frequency: 34 },
  { hanzi: "除了", pinyin: "chúle", english: "besides; except; in addition to", pos: "prep", frequency: 35 },
  { hanzi: "厨房", pinyin: "chúfáng", english: "kitchen", pos: "n", frequency: 36 },
  { hanzi: "春", pinyin: "chūn", english: "spring (season)", pos: "n", frequency: 37 },
  { hanzi: "词语", pinyin: "cíyǔ", english: "words; expression", pos: "n", frequency: 38 },
  { hanzi: "聪明", pinyin: "cōngming", english: "smart; clever; intelligent", pos: "adj", frequency: 39 },
  { hanzi: "打扫", pinyin: "dǎsǎo", english: "to clean; to sweep", pos: "v", frequency: 40 },
  { hanzi: "打算", pinyin: "dǎsuàn", english: "to plan; plan", pos: "v/n", frequency: 41 },
  { hanzi: "带", pinyin: "dài", english: "to bring; to carry; to lead", pos: "v", frequency: 42 },
  { hanzi: "担心", pinyin: "dānxīn", english: "to worry; to be concerned", pos: "v", frequency: 43 },
  { hanzi: "蛋糕", pinyin: "dàngāo", english: "cake", pos: "n", frequency: 44 },
  { hanzi: "当然", pinyin: "dāngrán", english: "of course; certainly", pos: "adv", frequency: 45 },
  { hanzi: "地", pinyin: "de", english: "adverbial particle", pos: "part", frequency: 46 },
  { hanzi: "灯", pinyin: "dēng", english: "lamp; light", pos: "n", frequency: 47 },
  { hanzi: "等", pinyin: "děng", english: "to wait; etc.", pos: "v/part", frequency: 48 },
  { hanzi: "低", pinyin: "dī", english: "low", pos: "adj", frequency: 49 },
  { hanzi: "地图", pinyin: "dìtú", english: "map", pos: "n", frequency: 50 },
  { hanzi: "电梯", pinyin: "diàntī", english: "elevator; lift", pos: "n", frequency: 51 },
  { hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", english: "email", pos: "n", frequency: 52 },
  { hanzi: "东", pinyin: "dōng", english: "east", pos: "n", frequency: 53 },
  { hanzi: "冬", pinyin: "dōng", english: "winter", pos: "n", frequency: 54 },
  { hanzi: "动物", pinyin: "dòngwù", english: "animal", pos: "n", frequency: 55 },
  { hanzi: "短", pinyin: "duǎn", english: "short (length)", pos: "adj", frequency: 56 },
  { hanzi: "段", pinyin: "duàn", english: "section; paragraph (measure word)", pos: "m", frequency: 57 },
  { hanzi: "锻炼", pinyin: "duànliàn", english: "to exercise; to work out", pos: "v", frequency: 58 },
  { hanzi: "多么", pinyin: "duōme", english: "how (exclamatory); what a", pos: "adv", frequency: 59 },
  { hanzi: "饿", pinyin: "è", english: "hungry", pos: "adj", frequency: 60 },
  { hanzi: "耳朵", pinyin: "ěrduo", english: "ear", pos: "n", frequency: 61 },
  { hanzi: "发烧", pinyin: "fāshāo", english: "to have a fever", pos: "v", frequency: 62 },
  { hanzi: "发现", pinyin: "fāxiàn", english: "to discover; to find", pos: "v", frequency: 63 },
  { hanzi: "方便", pinyin: "fāngbiàn", english: "convenient; handy", pos: "adj", frequency: 64 },
  { hanzi: "放", pinyin: "fàng", english: "to put; to place; to release", pos: "v", frequency: 65 },
  { hanzi: "放心", pinyin: "fàngxīn", english: "to feel at ease; to not worry", pos: "v", frequency: 66 },
  { hanzi: "分", pinyin: "fēn", english: "minute; cent; to divide", pos: "m/v", frequency: 67 },
  { hanzi: "复习", pinyin: "fùxí", english: "to review; to revise", pos: "v", frequency: 68 },
  { hanzi: "附近", pinyin: "fùjìn", english: "nearby; in the vicinity", pos: "n/adj", frequency: 69 },
  { hanzi: "干净", pinyin: "gānjìng", english: "clean; tidy", pos: "adj", frequency: 70 },
  { hanzi: "感冒", pinyin: "gǎnmào", english: "cold (illness); to catch a cold", pos: "n/v", frequency: 71 },
  { hanzi: "感兴趣", pinyin: "gǎn xìngqù", english: "to be interested in", pos: "v", frequency: 72 },
  { hanzi: "刚才", pinyin: "gāngcái", english: "just now; a moment ago", pos: "n", frequency: 73 },
  { hanzi: "个子", pinyin: "gèzi", english: "height; stature", pos: "n", frequency: 74 },
  { hanzi: "根据", pinyin: "gēnjù", english: "according to; based on", pos: "prep", frequency: 75 },
  { hanzi: "跟", pinyin: "gēn", english: "with; to follow; and", pos: "prep/conj", frequency: 76 },
  { hanzi: "更", pinyin: "gèng", english: "even more; still more", pos: "adv", frequency: 77 },
  { hanzi: "公斤", pinyin: "gōngjīn", english: "kilogram", pos: "m", frequency: 78 },
  { hanzi: "公里", pinyin: "gōnglǐ", english: "kilometer", pos: "m", frequency: 79 },
  { hanzi: "故事", pinyin: "gùshi", english: "story; tale", pos: "n", frequency: 80 },
  { hanzi: "刮风", pinyin: "guāfēng", english: "to be windy; the wind blows", pos: "v", frequency: 81 },
  { hanzi: "关", pinyin: "guān", english: "to close; to shut; to turn off", pos: "v", frequency: 82 },
  { hanzi: "关系", pinyin: "guānxi", english: "relationship; connection", pos: "n", frequency: 83 },
  { hanzi: "关心", pinyin: "guānxīn", english: "to care about; concern", pos: "v/n", frequency: 84 },
  { hanzi: "关注", pinyin: "guānzhù", english: "to pay attention to; to follow", pos: "v", frequency: 85 },
  { hanzi: "国家", pinyin: "guójiā", english: "country; nation", pos: "n", frequency: 86 },
  { hanzi: "果汁", pinyin: "guǒzhī", english: "fruit juice", pos: "n", frequency: 87 },
  { hanzi: "过去", pinyin: "guòqù", english: "past; in the past", pos: "n", frequency: 88 },
  { hanzi: "还是", pinyin: "háishi", english: "or; still; had better", pos: "conj/adv", frequency: 89 },
  { hanzi: "害怕", pinyin: "hàipà", english: "to be afraid; to fear", pos: "v", frequency: 90 },
  { hanzi: "河", pinyin: "hé", english: "river", pos: "n", frequency: 91 },
  { hanzi: "黑板", pinyin: "hēibǎn", english: "blackboard", pos: "n", frequency: 92 },
  { hanzi: "后来", pinyin: "hòulái", english: "afterward; later", pos: "adv", frequency: 93 },
  { hanzi: "护照", pinyin: "hùzhào", english: "passport", pos: "n", frequency: 94 },
  { hanzi: "花", pinyin: "huā", english: "flower; to spend (money/time)", pos: "n/v", frequency: 95 },
  { hanzi: "画", pinyin: "huà", english: "to draw; painting", pos: "v/n", frequency: 96 },
  { hanzi: "坏", pinyin: "huài", english: "bad; broken", pos: "adj", frequency: 97 },
  { hanzi: "欢迎", pinyin: "huānyíng", english: "to welcome; welcome", pos: "v/n", frequency: 98 },
  { hanzi: "还", pinyin: "huán", english: "to return (something)", pos: "v", frequency: 99 },
  { hanzi: "环境", pinyin: "huánjìng", english: "environment; surroundings", pos: "n", frequency: 100 },
  { hanzi: "换", pinyin: "huàn", english: "to change; to exchange", pos: "v", frequency: 101 },
  { hanzi: "黄", pinyin: "huáng", english: "yellow", pos: "adj", frequency: 102 },
  { hanzi: "回答", pinyin: "huídá", english: "to answer; to reply", pos: "v/n", frequency: 103 },
  { hanzi: "花园", pinyin: "huāyuán", english: "garden", pos: "n", frequency: 104 },
  { hanzi: "节目", pinyin: "jiémù", english: "program; show", pos: "n", frequency: 105 },
  { hanzi: "节日", pinyin: "jiérì", english: "holiday; festival", pos: "n", frequency: 106 },
  { hanzi: "结婚", pinyin: "jiéhūn", english: "to marry; to get married", pos: "v", frequency: 107 },
  { hanzi: "解决", pinyin: "jiějué", english: "to solve; to resolve", pos: "v", frequency: 108 },
  { hanzi: "借", pinyin: "jiè", english: "to borrow; to lend", pos: "v", frequency: 109 },
  { hanzi: "经常", pinyin: "jīngcháng", english: "often; frequently", pos: "adv", frequency: 110 },
  { hanzi: "经过", pinyin: "jīngguò", english: "to pass by; to go through", pos: "v/prep", frequency: 111 },
  { hanzi: "经理", pinyin: "jīnglǐ", english: "manager; director", pos: "n", frequency: 112 },
  { hanzi: "久", pinyin: "jiǔ", english: "long (time)", pos: "adj", frequency: 113 },
  { hanzi: "旧", pinyin: "jiù", english: "old; used; worn", pos: "adj", frequency: 114 },
  { hanzi: "句子", pinyin: "jùzi", english: "sentence", pos: "n", frequency: 115 },
  { hanzi: "觉得", pinyin: "juéde", english: "to feel; to think; to consider", pos: "v", frequency: 116 },
  { hanzi: "决定", pinyin: "juédìng", english: "to decide; decision", pos: "v/n", frequency: 117 },
  { hanzi: "渴", pinyin: "kě", english: "thirsty", pos: "adj", frequency: 118 },
  { hanzi: "可爱", pinyin: "kě'ài", english: "cute; lovable", pos: "adj", frequency: 119 },
  { hanzi: "客人", pinyin: "kèrén", english: "guest; visitor", pos: "n", frequency: 120 },
  { hanzi: "空调", pinyin: "kōngtiáo", english: "air conditioning", pos: "n", frequency: 121 },
  { hanzi: "口", pinyin: "kǒu", english: "mouth; (measure word for people)", pos: "n/m", frequency: 122 },
  { hanzi: "哭", pinyin: "kū", english: "to cry; to weep", pos: "v", frequency: 123 },
  { hanzi: "裤子", pinyin: "kùzi", english: "trousers; pants", pos: "n", frequency: 124 },
  { hanzi: "筷子", pinyin: "kuàizi", english: "chopsticks", pos: "n", frequency: 125 },
  { hanzi: "困", pinyin: "kùn", english: "sleepy; drowsy", pos: "adj", frequency: 126 },
  { hanzi: "蓝", pinyin: "lán", english: "blue", pos: "adj", frequency: 127 },
  { hanzi: "老", pinyin: "lǎo", english: "old; experienced", pos: "adj", frequency: 128 },
  { hanzi: "离开", pinyin: "líkāi", english: "to leave; to depart", pos: "v", frequency: 129 },
  { hanzi: "礼物", pinyin: "lǐwù", english: "gift; present", pos: "n", frequency: 130 },
  { hanzi: "历史", pinyin: "lìshǐ", english: "history", pos: "n", frequency: 131 },
  { hanzi: "脸", pinyin: "liǎn", english: "face", pos: "n", frequency: 132 },
  { hanzi: "练习", pinyin: "liànxí", english: "to practice; exercise", pos: "v/n", frequency: 133 },
  { hanzi: "了解", pinyin: "liǎojiě", english: "to understand; to know about", pos: "v", frequency: 134 },
  { hanzi: "邻居", pinyin: "línjū", english: "neighbor", pos: "n", frequency: 135 },
  { hanzi: "留", pinyin: "liú", english: "to stay; to leave behind", pos: "v", frequency: 136 },
  { hanzi: "楼", pinyin: "lóu", english: "building; floor (above ground)", pos: "n", frequency: 137 },
  { hanzi: "绿", pinyin: "lǜ", english: "green", pos: "adj", frequency: 138 },
  { hanzi: "马上", pinyin: "mǎshàng", english: "immediately; at once; soon", pos: "adv", frequency: 139 },
  { hanzi: "满意", pinyin: "mǎnyì", english: "satisfied; content", pos: "adj", frequency: 140 },
  { hanzi: "帽子", pinyin: "màozi", english: "hat; cap", pos: "n", frequency: 141 },
  { hanzi: "相同", pinyin: "xiāngtóng", english: "identical; same", pos: "adj", frequency: 142 },
  { hanzi: "声音", pinyin: "shēngyīn", english: "sound; voice", pos: "n", frequency: 143 },
  { hanzi: "树", pinyin: "shù", english: "tree", pos: "n", frequency: 144 },
  { hanzi: "数学", pinyin: "shùxué", english: "mathematics; math", pos: "n", frequency: 145 },
  { hanzi: "刷牙", pinyin: "shuāyá", english: "to brush teeth", pos: "v", frequency: 146 },
  { hanzi: "双", pinyin: "shuāng", english: "pair; double (measure word)", pos: "m/adj", frequency: 147 },
  { hanzi: "水平", pinyin: "shuǐpíng", english: "level; standard", pos: "n", frequency: 148 },
  { hanzi: "司机", pinyin: "sījī", english: "driver; chauffeur", pos: "n", frequency: 149 },
  { hanzi: "太阳", pinyin: "tàiyáng", english: "sun", pos: "n", frequency: 150 },
  { hanzi: "特别", pinyin: "tèbié", english: "special; especially", pos: "adj/adv", frequency: 151 },
  { hanzi: "疼", pinyin: "téng", english: "to ache; to hurt; sore", pos: "v/adj", frequency: 152 },
  { hanzi: "提", pinyin: "tí", english: "to carry; to raise; to mention", pos: "v", frequency: 153 },
  { hanzi: "体育", pinyin: "tǐyù", english: "sports; physical education", pos: "n", frequency: 154 },
  { hanzi: "天", pinyin: "tiān", english: "day; sky; heaven", pos: "n/m", frequency: 155 },
  { hanzi: "甜", pinyin: "tián", english: "sweet", pos: "adj", frequency: 156 },
  { hanzi: "条", pinyin: "tiáo", english: "(measure word for long objects)", pos: "m", frequency: 157 },
  { hanzi: "同事", pinyin: "tóngshì", english: "colleague; coworker", pos: "n", frequency: 158 },
  { hanzi: "同意", pinyin: "tóngyì", english: "to agree; agreement", pos: "v/n", frequency: 159 },
  { hanzi: "图书馆", pinyin: "túshūguǎn", english: "library", pos: "n", frequency: 160 },
  { hanzi: "腿", pinyin: "tuǐ", english: "leg", pos: "n", frequency: 161 },
  { hanzi: "完成", pinyin: "wánchéng", english: "to complete; to finish", pos: "v", frequency: 162 },
  { hanzi: "碗", pinyin: "wǎn", english: "bowl (measure word)", pos: "n/m", frequency: 163 },
  { hanzi: "万", pinyin: "wàn", english: "ten thousand", pos: "num", frequency: 164 },
  { hanzi: "忘", pinyin: "wàng", english: "to forget", pos: "v", frequency: 165 },
  { hanzi: "位", pinyin: "wèi", english: "(polite measure word for people)", pos: "m", frequency: 166 },
  { hanzi: "文化", pinyin: "wénhuà", english: "culture; civilization", pos: "n", frequency: 167 },
  { hanzi: "西", pinyin: "xī", english: "west", pos: "n", frequency: 168 },
  { hanzi: "习惯", pinyin: "xíguàn", english: "habit; custom; to be used to", pos: "n/v", frequency: 169 },
  { hanzi: "洗手间", pinyin: "xǐshǒujiān", english: "restroom; washroom", pos: "n", frequency: 170 },
  { hanzi: "洗澡", pinyin: "xǐzǎo", english: "to bathe; to take a shower", pos: "v", frequency: 171 },
  { hanzi: "夏", pinyin: "xià", english: "summer", pos: "n", frequency: 172 },
  { hanzi: "相信", pinyin: "xiāngxìn", english: "to believe; to trust", pos: "v", frequency: 173 },
  { hanzi: "香蕉", pinyin: "xiāngjiāo", english: "banana", pos: "n", frequency: 174 },
  { hanzi: "像", pinyin: "xiàng", english: "to resemble; like; as", pos: "v/prep", frequency: 175 },
  { hanzi: "小心", pinyin: "xiǎoxīn", english: "careful; to be careful", pos: "adj/v", frequency: 176 },
  { hanzi: "校长", pinyin: "xiàozhǎng", english: "school principal; president", pos: "n", frequency: 177 },
  { hanzi: "新闻", pinyin: "xīnwén", english: "news", pos: "n", frequency: 178 },
  { hanzi: "行李箱", pinyin: "xínglǐxiāng", english: "suitcase; luggage", pos: "n", frequency: 179 },
  { hanzi: "熊猫", pinyin: "xióngmāo", english: "panda", pos: "n", frequency: 180 },
  { hanzi: "需要", pinyin: "xūyào", english: "to need; to require", pos: "v/n", frequency: 181 },
  { hanzi: "选择", pinyin: "xuǎnzé", english: "to choose; choice", pos: "v/n", frequency: 182 },
  { hanzi: "牙", pinyin: "yá", english: "tooth; teeth", pos: "n", frequency: 183 },
  { hanzi: "颜色", pinyin: "yánsè", english: "color", pos: "n", frequency: 184 },
  { hanzi: "眼镜", pinyin: "yǎnjìng", english: "glasses; spectacles", pos: "n", frequency: 185 },
  { hanzi: "一般", pinyin: "yībān", english: "ordinary; general; usually", pos: "adj/adv", frequency: 186 },
  { hanzi: "一共", pinyin: "yīgòng", english: "altogether; in total", pos: "adv", frequency: 187 },
  { hanzi: "一样", pinyin: "yīyàng", english: "same; alike", pos: "adj", frequency: 188 },
  { hanzi: "以前", pinyin: "yǐqián", english: "before; previously; in the past", pos: "n", frequency: 189 },
  { hanzi: "以为", pinyin: "yǐwéi", english: "to think; to believe (mistakenly)", pos: "v", frequency: 190 },
  { hanzi: "音乐", pinyin: "yīnyuè", english: "music", pos: "n", frequency: 191 },
  { hanzi: "银行", pinyin: "yínháng", english: "bank", pos: "n", frequency: 192 },
  { hanzi: "应该", pinyin: "yīnggāi", english: "should; ought to", pos: "aux", frequency: 193 },
  { hanzi: "影响", pinyin: "yǐngxiǎng", english: "to influence; influence; effect", pos: "v/n", frequency: 194 },
  { hanzi: "用", pinyin: "yòng", english: "to use; with", pos: "v/prep", frequency: 195 },
  { hanzi: "邮局", pinyin: "yóujú", english: "post office", pos: "n", frequency: 196 },
  { hanzi: "有名", pinyin: "yǒumíng", english: "famous; well-known", pos: "adj", frequency: 197 },
  { hanzi: "又", pinyin: "yòu", english: "again; also; and", pos: "adv", frequency: 198 },
  { hanzi: "遇到", pinyin: "yùdào", english: "to encounter; to meet", pos: "v", frequency: 199 },
  { hanzi: "原来", pinyin: "yuánlái", english: "originally; as it turns out", pos: "adv/adj", frequency: 200 },
  { hanzi: "月亮", pinyin: "yuèliang", english: "moon", pos: "n", frequency: 201 },
  { hanzi: "越", pinyin: "yuè", english: "the more…the more", pos: "adv", frequency: 202 },
  { hanzi: "站", pinyin: "zhàn", english: "to stand; station; stop", pos: "v/n", frequency: 203 },
  { hanzi: "张", pinyin: "zhāng", english: "(measure word for flat objects)", pos: "m", frequency: 204 },
  { hanzi: "长", pinyin: "zhǎng", english: "to grow; to develop", pos: "v", frequency: 205 },
  { hanzi: "着急", pinyin: "zháojí", english: "to be anxious; to worry", pos: "v", frequency: 206 },
  { hanzi: "这么", pinyin: "zhème", english: "so; such; this way", pos: "adv", frequency: 207 },
  { hanzi: "只", pinyin: "zhǐ", english: "only; just", pos: "adv", frequency: 208 },
  { hanzi: "中间", pinyin: "zhōngjiān", english: "middle; center; between", pos: "n", frequency: 209 },
  { hanzi: "终于", pinyin: "zhōngyú", english: "finally; at last", pos: "adv", frequency: 210 },
  { hanzi: "种", pinyin: "zhǒng", english: "kind; type (measure word for types)", pos: "m/n", frequency: 211 },
  { hanzi: "重要", pinyin: "zhòngyào", english: "important", pos: "adj", frequency: 212 },
  { hanzi: "自己", pinyin: "zìjǐ", english: "oneself; self", pos: "pron", frequency: 213 },
  { hanzi: "总是", pinyin: "zǒngshì", english: "always", pos: "adv", frequency: 214 },
  { hanzi: "嘴", pinyin: "zuǐ", english: "mouth; beak", pos: "n", frequency: 215 },
  { hanzi: "最后", pinyin: "zuìhòu", english: "final; last; finally", pos: "adj/adv", frequency: 216 },
  { hanzi: "最近", pinyin: "zuìjìn", english: "recently; lately; soon", pos: "adv/adj", frequency: 217 },
  { hanzi: "作业", pinyin: "zuòyè", english: "homework; assignment", pos: "n", frequency: 218 },
];
