import type { RawWord } from "../parse-hsk-data";

export const hsk4Words: RawWord[] = [
  { hanzi: "爱情", pinyin: "àiqíng", english: "love (romantic)", pos: "n", frequency: 1 },
  { hanzi: "安排", pinyin: "ānpái", english: "to arrange; arrangement", pos: "v/n", frequency: 2 },
  { hanzi: "按照", pinyin: "ànzhào", english: "according to; in accordance with", pos: "prep", frequency: 3 },
  { hanzi: "白", pinyin: "bái", english: "in vain; for nothing", pos: "adv", frequency: 4 },
  { hanzi: "班长", pinyin: "bānzhǎng", english: "class monitor; team leader", pos: "n", frequency: 5 },
  { hanzi: "搬", pinyin: "bān", english: "to move (objects/residence)", pos: "v", frequency: 6 },
  { hanzi: "棒", pinyin: "bàng", english: "excellent; great; strong", pos: "adj", frequency: 7 },
  { hanzi: "包括", pinyin: "bāokuò", english: "to include; including", pos: "v", frequency: 8 },
  { hanzi: "保护", pinyin: "bǎohù", english: "to protect; protection", pos: "v/n", frequency: 9 },
  { hanzi: "保证", pinyin: "bǎozhèng", english: "to guarantee; guarantee", pos: "v/n", frequency: 10 },
  { hanzi: "报道", pinyin: "bàodào", english: "to report (news); report", pos: "v/n", frequency: 11 },
  { hanzi: "报名", pinyin: "bàomíng", english: "to sign up; to register", pos: "v", frequency: 12 },
  { hanzi: "背", pinyin: "bèi", english: "to memorize; to recite", pos: "v", frequency: 13 },
  { hanzi: "本来", pinyin: "běnlái", english: "originally; at first", pos: "adv", frequency: 14 },
  { hanzi: "笨", pinyin: "bèn", english: "stupid; clumsy", pos: "adj", frequency: 15 },
  { hanzi: "比较", pinyin: "bǐjiào", english: "comparatively; to compare", pos: "adv/v", frequency: 16 },
  { hanzi: "毕业", pinyin: "bìyè", english: "to graduate; graduation", pos: "v/n", frequency: 17 },
  { hanzi: "博士", pinyin: "bóshì", english: "doctorate; PhD", pos: "n", frequency: 18 },
  { hanzi: "不得不", pinyin: "bùdébù", english: "have to; cannot but", pos: "adv", frequency: 19 },
  { hanzi: "不管", pinyin: "bùguǎn", english: "no matter; regardless of", pos: "conj", frequency: 20 },
  { hanzi: "不仅", pinyin: "bùjǐn", english: "not only", pos: "adv", frequency: 21 },
  { hanzi: "部分", pinyin: "bùfen", english: "part; portion; section", pos: "n", frequency: 22 },
  { hanzi: "猜", pinyin: "cāi", english: "to guess", pos: "v", frequency: 23 },
  { hanzi: "材料", pinyin: "cáiliào", english: "material; data; ingredient", pos: "n", frequency: 24 },
  { hanzi: "尝", pinyin: "cháng", english: "to taste; to try", pos: "v", frequency: 25 },
  { hanzi: "场", pinyin: "chǎng", english: "(measure word for events/performances)", pos: "m", frequency: 26 },
  { hanzi: "超过", pinyin: "chāoguò", english: "to exceed; to surpass", pos: "v", frequency: 27 },
  { hanzi: "成功", pinyin: "chénggōng", english: "to succeed; success", pos: "v/n", frequency: 28 },
  { hanzi: "成为", pinyin: "chéngwéi", english: "to become", pos: "v", frequency: 29 },
  { hanzi: "诚实", pinyin: "chéngshí", english: "honest; truthful", pos: "adj", frequency: 30 },
  { hanzi: "乘坐", pinyin: "chéngzuò", english: "to travel by (vehicle)", pos: "v", frequency: 31 },
  { hanzi: "吃惊", pinyin: "chījīng", english: "to be surprised; to be shocked", pos: "v", frequency: 32 },
  { hanzi: "重新", pinyin: "chóngxīn", english: "again; anew; afresh", pos: "adv", frequency: 33 },
  { hanzi: "抽烟", pinyin: "chōuyān", english: "to smoke (cigarettes)", pos: "v", frequency: 34 },
  { hanzi: "出发", pinyin: "chūfā", english: "to set off; to depart", pos: "v", frequency: 35 },
  { hanzi: "出现", pinyin: "chūxiàn", english: "to appear; to emerge", pos: "v", frequency: 36 },
  { hanzi: "传统", pinyin: "chuántǒng", english: "tradition; traditional", pos: "n/adj", frequency: 37 },
  { hanzi: "窗户", pinyin: "chuānghù", english: "window", pos: "n", frequency: 38 },
  { hanzi: "词典", pinyin: "cídiǎn", english: "dictionary", pos: "n", frequency: 39 },
  { hanzi: "从来", pinyin: "cónglái", english: "always; at all times (with negation: never)", pos: "adv", frequency: 40 },
  { hanzi: "粗心", pinyin: "cūxīn", english: "careless; inattentive", pos: "adj", frequency: 41 },
  { hanzi: "存", pinyin: "cún", english: "to save; to deposit; to store", pos: "v", frequency: 42 },
  { hanzi: "错误", pinyin: "cuòwù", english: "mistake; error; wrong", pos: "n/adj", frequency: 43 },
  { hanzi: "答案", pinyin: "dá'àn", english: "answer; solution", pos: "n", frequency: 44 },
  { hanzi: "打扰", pinyin: "dǎrǎo", english: "to disturb; to bother", pos: "v", frequency: 45 },
  { hanzi: "打折", pinyin: "dǎzhé", english: "to discount; discount", pos: "v/n", frequency: 46 },
  { hanzi: "打招呼", pinyin: "dǎ zhāohu", english: "to greet; to say hello", pos: "v", frequency: 47 },
  { hanzi: "大概", pinyin: "dàgài", english: "probably; approximately", pos: "adv", frequency: 48 },
  { hanzi: "大使馆", pinyin: "dàshǐguǎn", english: "embassy", pos: "n", frequency: 49 },
  { hanzi: "大夫", pinyin: "dàifu", english: "doctor; physician", pos: "n", frequency: 50 },
  { hanzi: "大约", pinyin: "dàyuē", english: "approximately; about", pos: "adv", frequency: 51 },
  { hanzi: "代表", pinyin: "dàibiǎo", english: "to represent; representative", pos: "v/n", frequency: 52 },
  { hanzi: "戴", pinyin: "dài", english: "to wear (accessories)", pos: "v", frequency: 53 },
  { hanzi: "当", pinyin: "dāng", english: "to serve as; when; at the time", pos: "v/prep", frequency: 54 },
  { hanzi: "道歉", pinyin: "dàoqiàn", english: "to apologize", pos: "v", frequency: 55 },
  { hanzi: "得意", pinyin: "déyì", english: "proud of oneself; complacent", pos: "adj", frequency: 56 },
  { hanzi: "得罪", pinyin: "dézuì", english: "to offend; to displease", pos: "v", frequency: 57 },
  { hanzi: "登机牌", pinyin: "dēngjī pái", english: "boarding pass", pos: "n", frequency: 58 },
  { hanzi: "地球", pinyin: "dìqiú", english: "Earth; the globe", pos: "n", frequency: 59 },
  { hanzi: "地址", pinyin: "dìzhǐ", english: "address", pos: "n", frequency: 60 },
  { hanzi: "掉", pinyin: "diào", english: "to fall; to drop; to lose", pos: "v", frequency: 61 },
  { hanzi: "调查", pinyin: "diàochá", english: "to investigate; investigation; survey", pos: "v/n", frequency: 62 },
  { hanzi: "动作", pinyin: "dòngzuò", english: "action; movement", pos: "n", frequency: 63 },
  { hanzi: "堵车", pinyin: "dǔchē", english: "traffic jam", pos: "n/v", frequency: 64 },
  { hanzi: "肚子", pinyin: "dùzi", english: "belly; stomach", pos: "n", frequency: 65 },
  { hanzi: "对于", pinyin: "duìyú", english: "regarding; as for; in terms of", pos: "prep", frequency: 66 },
  { hanzi: "而", pinyin: "ér", english: "and; but; yet (conjunction)", pos: "conj", frequency: 67 },
  { hanzi: "发展", pinyin: "fāzhǎn", english: "to develop; development", pos: "v/n", frequency: 68 },
  { hanzi: "方法", pinyin: "fāngfǎ", english: "method; approach; way", pos: "n", frequency: 69 },
  { hanzi: "方向", pinyin: "fāngxiàng", english: "direction; orientation", pos: "n", frequency: 70 },
  { hanzi: "否则", pinyin: "fǒuzé", english: "otherwise; or else", pos: "conj", frequency: 71 },
  { hanzi: "符合", pinyin: "fúhé", english: "to conform to; to comply with", pos: "v", frequency: 72 },
  { hanzi: "父亲", pinyin: "fùqīn", english: "father (formal)", pos: "n", frequency: 73 },
  { hanzi: "负责", pinyin: "fùzé", english: "to be responsible for", pos: "v", frequency: 74 },
  { hanzi: "复杂", pinyin: "fùzá", english: "complex; complicated", pos: "adj", frequency: 75 },
  { hanzi: "富", pinyin: "fù", english: "rich; wealthy", pos: "adj", frequency: 76 },
  { hanzi: "感谢", pinyin: "gǎnxiè", english: "to thank; gratitude", pos: "v/n", frequency: 77 },
  { hanzi: "各", pinyin: "gè", english: "each; every; various", pos: "det", frequency: 78 },
  { hanzi: "个人", pinyin: "gèrén", english: "individual; personal", pos: "n/adj", frequency: 79 },
  { hanzi: "公里", pinyin: "gōnglǐ", english: "kilometer", pos: "m", frequency: 80 },
  { hanzi: "功夫", pinyin: "gōngfu", english: "kung fu; skill; time/effort", pos: "n", frequency: 81 },
  { hanzi: "共同", pinyin: "gòngtóng", english: "common; joint; together", pos: "adj/adv", frequency: 82 },
  { hanzi: "购物", pinyin: "gòuwù", english: "to shop; shopping", pos: "v/n", frequency: 83 },
  { hanzi: "估计", pinyin: "gūjì", english: "to estimate; estimation", pos: "v/n", frequency: 84 },
  { hanzi: "顾客", pinyin: "gùkè", english: "customer; client", pos: "n", frequency: 85 },
  { hanzi: "观众", pinyin: "guānzhòng", english: "audience; spectators", pos: "n", frequency: 86 },
  { hanzi: "管理", pinyin: "guǎnlǐ", english: "to manage; management", pos: "v/n", frequency: 87 },
  { hanzi: "规定", pinyin: "guīdìng", english: "to stipulate; regulation; rule", pos: "v/n", frequency: 88 },
  { hanzi: "国际", pinyin: "guójì", english: "international", pos: "adj/n", frequency: 89 },
  { hanzi: "过程", pinyin: "guòchéng", english: "process; course", pos: "n", frequency: 90 },
  { hanzi: "过敏", pinyin: "guòmǐn", english: "allergy; to be allergic", pos: "n/v", frequency: 91 },
  { hanzi: "海洋", pinyin: "hǎiyáng", english: "ocean; sea", pos: "n", frequency: 92 },
  { hanzi: "含义", pinyin: "hányì", english: "meaning; implication", pos: "n", frequency: 93 },
  { hanzi: "好处", pinyin: "hǎochu", english: "benefit; advantage", pos: "n", frequency: 94 },
  { hanzi: "好像", pinyin: "hǎoxiàng", english: "to seem; to be like; as if", pos: "v/adv", frequency: 95 },
  { hanzi: "号码", pinyin: "hàomǎ", english: "number (phone/room/etc.)", pos: "n", frequency: 96 },
  { hanzi: "合适", pinyin: "héshì", english: "suitable; appropriate", pos: "adj", frequency: 97 },
  { hanzi: "后悔", pinyin: "hòuhuǐ", english: "to regret; regret", pos: "v/n", frequency: 98 },
  { hanzi: "互联网", pinyin: "hùliánwǎng", english: "internet", pos: "n", frequency: 99 },
  { hanzi: "互相", pinyin: "hùxiāng", english: "mutually; each other", pos: "adv", frequency: 100 },
  { hanzi: "获得", pinyin: "huòdé", english: "to obtain; to gain; to acquire", pos: "v", frequency: 101 },
  { hanzi: "积极", pinyin: "jījí", english: "active; positive; enthusiastic", pos: "adj", frequency: 102 },
  { hanzi: "基础", pinyin: "jīchǔ", english: "foundation; base; basic", pos: "n/adj", frequency: 103 },
  { hanzi: "即使", pinyin: "jíshǐ", english: "even if; even though", pos: "conj", frequency: 104 },
  { hanzi: "计划", pinyin: "jìhuà", english: "plan; to plan", pos: "n/v", frequency: 105 },
  { hanzi: "记者", pinyin: "jìzhě", english: "journalist; reporter", pos: "n", frequency: 106 },
  { hanzi: "技术", pinyin: "jìshù", english: "technology; technique; skill", pos: "n", frequency: 107 },
  { hanzi: "既然", pinyin: "jìrán", english: "since; given that", pos: "conj", frequency: 108 },
  { hanzi: "坚持", pinyin: "jiānchí", english: "to persist; to insist; to uphold", pos: "v", frequency: 109 },
  { hanzi: "建议", pinyin: "jiànyì", english: "to suggest; suggestion", pos: "v/n", frequency: 110 },
  { hanzi: "将来", pinyin: "jiānglái", english: "future; in the future", pos: "n", frequency: 111 },
  { hanzi: "奖金", pinyin: "jiǎngjīn", english: "bonus; prize money", pos: "n", frequency: 112 },
  { hanzi: "降低", pinyin: "jiàngdī", english: "to reduce; to lower; to decrease", pos: "v", frequency: 113 },
  { hanzi: "交", pinyin: "jiāo", english: "to hand over; to submit; to make (friends)", pos: "v", frequency: 114 },
  { hanzi: "交流", pinyin: "jiāoliú", english: "to exchange; exchange; communication", pos: "v/n", frequency: 115 },
  { hanzi: "教授", pinyin: "jiàoshòu", english: "professor", pos: "n", frequency: 116 },
  { hanzi: "教育", pinyin: "jiàoyù", english: "education; to educate", pos: "n/v", frequency: 117 },
  { hanzi: "接受", pinyin: "jiēshòu", english: "to accept; to receive", pos: "v", frequency: 118 },
  { hanzi: "结果", pinyin: "jiéguǒ", english: "result; outcome; as a result", pos: "n/conj", frequency: 119 },
  { hanzi: "解释", pinyin: "jiěshì", english: "to explain; explanation", pos: "v/n", frequency: 120 },
  { hanzi: "尽管", pinyin: "jǐnguǎn", english: "although; even though; feel free to", pos: "conj/adv", frequency: 121 },
  { hanzi: "经济", pinyin: "jīngjì", english: "economy; economic", pos: "n/adj", frequency: 122 },
  { hanzi: "竟然", pinyin: "jìngrán", english: "unexpectedly; surprisingly", pos: "adv", frequency: 123 },
  { hanzi: "举", pinyin: "jǔ", english: "to raise; to lift; to cite", pos: "v", frequency: 124 },
  { hanzi: "举办", pinyin: "jǔbàn", english: "to hold (event); to host", pos: "v", frequency: 125 },
  { hanzi: "拒绝", pinyin: "jùjué", english: "to refuse; to decline; to reject", pos: "v", frequency: 126 },
  { hanzi: "距离", pinyin: "jùlí", english: "distance; gap; to be away from", pos: "n/v", frequency: 127 },
  { hanzi: "开心", pinyin: "kāixīn", english: "happy; joyful", pos: "adj", frequency: 128 },
  { hanzi: "科学", pinyin: "kēxué", english: "science; scientific", pos: "n/adj", frequency: 129 },
  { hanzi: "肯定", pinyin: "kěndìng", english: "definitely; to affirm; certain", pos: "adv/v/adj", frequency: 130 },
  { hanzi: "空气", pinyin: "kōngqì", english: "air; atmosphere", pos: "n", frequency: 131 },
  { hanzi: "空闲", pinyin: "kòngxián", english: "free time; leisure", pos: "n/adj", frequency: 132 },
  { hanzi: "恐怕", pinyin: "kǒngpà", english: "I'm afraid; probably", pos: "adv", frequency: 133 },
  { hanzi: "苦", pinyin: "kǔ", english: "bitter; hardship", pos: "adj/n", frequency: 134 },
  { hanzi: "困难", pinyin: "kùnnán", english: "difficulty; difficult", pos: "n/adj", frequency: 135 },
  { hanzi: "来不及", pinyin: "lái bu jí", english: "not have enough time; too late", pos: "v", frequency: 136 },
  { hanzi: "来得及", pinyin: "lái de jí", english: "to have enough time; not too late", pos: "v", frequency: 137 },
  { hanzi: "浪费", pinyin: "làngfèi", english: "to waste; wasteful", pos: "v/adj", frequency: 138 },
  { hanzi: "乐观", pinyin: "lèguān", english: "optimistic", pos: "adj", frequency: 139 },
  { hanzi: "联系", pinyin: "liánxì", english: "to contact; connection; to relate", pos: "v/n", frequency: 140 },
  { hanzi: "量", pinyin: "liàng", english: "quantity; amount", pos: "n", frequency: 141 },
  { hanzi: "临时", pinyin: "línshí", english: "temporary; at the last moment", pos: "adj/adv", frequency: 142 },
  { hanzi: "领导", pinyin: "lǐngdǎo", english: "leader; to lead", pos: "n/v", frequency: 143 },
  { hanzi: "流行", pinyin: "liúxíng", english: "popular; fashionable; to spread", pos: "adj/v", frequency: 144 },
  { hanzi: "马虎", pinyin: "mǎhu", english: "careless; sloppy", pos: "adj", frequency: 145 },
  { hanzi: "麻烦", pinyin: "máfan", english: "trouble; troublesome; to bother", pos: "n/adj/v", frequency: 146 },
  { hanzi: "母亲", pinyin: "mǔqīn", english: "mother (formal)", pos: "n", frequency: 147 },
  { hanzi: "目的", pinyin: "mùdì", english: "purpose; goal; objective", pos: "n", frequency: 148 },
  { hanzi: "耐心", pinyin: "nàixīn", english: "patient; patience", pos: "adj/n", frequency: 149 },
  { hanzi: "难道", pinyin: "nándào", english: "could it be that; don't tell me", pos: "adv", frequency: 150 },
  { hanzi: "难受", pinyin: "nánshòu", english: "uncomfortable; feeling bad", pos: "adj", frequency: 151 },
  { hanzi: "内容", pinyin: "nèiróng", english: "content; substance", pos: "n", frequency: 152 },
  { hanzi: "能力", pinyin: "nénglì", english: "ability; capability", pos: "n", frequency: 153 },
  { hanzi: "年龄", pinyin: "niánlíng", english: "age", pos: "n", frequency: 154 },
  { hanzi: "努力", pinyin: "nǔlì", english: "to work hard; diligent; effort", pos: "v/adj/n", frequency: 155 },
  { hanzi: "判断", pinyin: "pànduàn", english: "to judge; judgment", pos: "v/n", frequency: 156 },
  { hanzi: "培养", pinyin: "péiyǎng", english: "to cultivate; to foster; to train", pos: "v", frequency: 157 },
  { hanzi: "批评", pinyin: "pīpíng", english: "to criticize; criticism", pos: "v/n", frequency: 158 },
  { hanzi: "皮肤", pinyin: "pífū", english: "skin", pos: "n", frequency: 159 },
  { hanzi: "脾气", pinyin: "píqi", english: "temper; disposition", pos: "n", frequency: 160 },
  { hanzi: "品质", pinyin: "pǐnzhì", english: "quality; character", pos: "n", frequency: 161 },
  { hanzi: "平时", pinyin: "píngshí", english: "normally; usually; at ordinary times", pos: "n", frequency: 162 },
  { hanzi: "破坏", pinyin: "pòhuài", english: "to destroy; to damage; sabotage", pos: "v/n", frequency: 163 },
  { hanzi: "其实", pinyin: "qíshí", english: "actually; in fact; as a matter of fact", pos: "adv", frequency: 164 },
  { hanzi: "其中", pinyin: "qízhōng", english: "among them; in it; within", pos: "prep", frequency: 165 },
  { hanzi: "气候", pinyin: "qìhòu", english: "climate", pos: "n", frequency: 166 },
  { hanzi: "签证", pinyin: "qiānzhèng", english: "visa", pos: "n", frequency: 167 },
  { hanzi: "亲戚", pinyin: "qīnqi", english: "relatives; kin", pos: "n", frequency: 168 },
  { hanzi: "轻", pinyin: "qīng", english: "light (weight); gentle", pos: "adj", frequency: 169 },
  { hanzi: "情况", pinyin: "qíngkuàng", english: "situation; circumstances", pos: "n", frequency: 170 },
  { hanzi: "请假", pinyin: "qǐngjià", english: "to ask for leave", pos: "v", frequency: 171 },
  { hanzi: "取", pinyin: "qǔ", english: "to take; to get; to fetch", pos: "v", frequency: 172 },
  { hanzi: "全部", pinyin: "quánbù", english: "all; entire; whole", pos: "adj/n", frequency: 173 },
  { hanzi: "缺点", pinyin: "quēdiǎn", english: "shortcoming; defect; weakness", pos: "n", frequency: 174 },
  { hanzi: "确实", pinyin: "quèshí", english: "indeed; really; truly", pos: "adv", frequency: 175 },
  { hanzi: "然而", pinyin: "rán'ér", english: "however; nevertheless; yet", pos: "conj", frequency: 176 },
  { hanzi: "热闹", pinyin: "rènao", english: "lively; bustling; exciting", pos: "adj", frequency: 177 },
  { hanzi: "认为", pinyin: "rènwéi", english: "to think; to consider; to believe", pos: "v", frequency: 178 },
  { hanzi: "任何", pinyin: "rènhé", english: "any; whatever; whichever", pos: "det", frequency: 179 },
  { hanzi: "扔", pinyin: "rēng", english: "to throw; to toss; to discard", pos: "v", frequency: 180 },
  { hanzi: "仍然", pinyin: "réngrán", english: "still; yet; as before", pos: "adv", frequency: 181 },
  { hanzi: "容易", pinyin: "róngyì", english: "easy; likely", pos: "adj", frequency: 182 },
  { hanzi: "如何", pinyin: "rúhé", english: "how; in what way", pos: "pron", frequency: 183 },
  { hanzi: "入口", pinyin: "rùkǒu", english: "entrance; entry", pos: "n", frequency: 184 },
  { hanzi: "散步", pinyin: "sànbù", english: "to take a walk; to stroll", pos: "v", frequency: 185 },
  { hanzi: "申请", pinyin: "shēnqǐng", english: "to apply; application", pos: "v/n", frequency: 186 },
  { hanzi: "深", pinyin: "shēn", english: "deep; profound; dark (color)", pos: "adj", frequency: 187 },
  { hanzi: "生活", pinyin: "shēnghuó", english: "life; to live; livelihood", pos: "n/v", frequency: 188 },
  { hanzi: "省", pinyin: "shěng", english: "province; to save; to economize", pos: "n/v", frequency: 189 },
  { hanzi: "失败", pinyin: "shībài", english: "to fail; failure", pos: "v/n", frequency: 190 },
  { hanzi: "失望", pinyin: "shīwàng", english: "disappointed; to lose hope", pos: "adj/v", frequency: 191 },
  { hanzi: "使", pinyin: "shǐ", english: "to make; to cause; to use", pos: "v", frequency: 192 },
  { hanzi: "是否", pinyin: "shìfǒu", english: "whether or not; if", pos: "conj", frequency: 193 },
  { hanzi: "适合", pinyin: "shìhé", english: "to suit; to be appropriate for", pos: "v", frequency: 194 },
  { hanzi: "收入", pinyin: "shōurù", english: "income; revenue", pos: "n", frequency: 195 },
  { hanzi: "输", pinyin: "shū", english: "to lose (a game/bet)", pos: "v", frequency: 196 },
  { hanzi: "熟悉", pinyin: "shúxī", english: "familiar with; to know well", pos: "adj/v", frequency: 197 },
  { hanzi: "数量", pinyin: "shùliàng", english: "quantity; number; amount", pos: "n", frequency: 198 },
  { hanzi: "顺利", pinyin: "shùnlì", english: "smooth; successful; without a hitch", pos: "adj", frequency: 199 },
  { hanzi: "说明", pinyin: "shuōmíng", english: "to explain; instructions; explanation", pos: "v/n", frequency: 200 },
];
