import type { RawWord } from "../parse-hsk-data";

export const hsk5Words: RawWord[] = [
  { hanzi: "爱护", pinyin: "àihù", english: "to cherish; to take good care of", pos: "v", frequency: 1 },
  { hanzi: "安慰", pinyin: "ānwèi", english: "to comfort; to console", pos: "v", frequency: 2 },
  { hanzi: "暗", pinyin: "àn", english: "dark; dim; secret", pos: "adj", frequency: 3 },
  { hanzi: "把握", pinyin: "bǎwò", english: "to grasp; confidence; certainty", pos: "v/n", frequency: 4 },
  { hanzi: "摆", pinyin: "bǎi", english: "to place; to arrange; to sway", pos: "v", frequency: 5 },
  { hanzi: "办理", pinyin: "bànlǐ", english: "to handle; to process; to conduct", pos: "v", frequency: 6 },
  { hanzi: "宝贝", pinyin: "bǎobèi", english: "baby; treasure; darling", pos: "n", frequency: 7 },
  { hanzi: "悲观", pinyin: "bēiguān", english: "pessimistic", pos: "adj", frequency: 8 },
  { hanzi: "本质", pinyin: "běnzhì", english: "nature; essence", pos: "n", frequency: 9 },
  { hanzi: "彼此", pinyin: "bǐcǐ", english: "each other; one another", pos: "pron", frequency: 10 },
  { hanzi: "边界", pinyin: "biānjiè", english: "boundary; border", pos: "n", frequency: 11 },
  { hanzi: "标准", pinyin: "biāozhǔn", english: "standard; criterion", pos: "n/adj", frequency: 12 },
  { hanzi: "表达", pinyin: "biǎodá", english: "to express; to convey", pos: "v", frequency: 13 },
  { hanzi: "表面", pinyin: "biǎomiàn", english: "surface; appearance; superficial", pos: "n/adj", frequency: 14 },
  { hanzi: "并且", pinyin: "bìngqiě", english: "and; moreover; furthermore", pos: "conj", frequency: 15 },
  { hanzi: "不断", pinyin: "bùduàn", english: "continuously; constantly", pos: "adv", frequency: 16 },
  { hanzi: "不免", pinyin: "bùmiǎn", english: "inevitably; cannot help but", pos: "adv", frequency: 17 },
  { hanzi: "不耐烦", pinyin: "bù nàifán", english: "impatient; annoyed", pos: "adj", frequency: 18 },
  { hanzi: "财产", pinyin: "cáichǎn", english: "property; assets", pos: "n", frequency: 19 },
  { hanzi: "采取", pinyin: "cǎiqǔ", english: "to adopt; to take (measures)", pos: "v", frequency: 20 },
  { hanzi: "参考", pinyin: "cānkǎo", english: "to refer to; reference", pos: "v/n", frequency: 21 },
  { hanzi: "层次", pinyin: "céngcì", english: "level; rank; layer", pos: "n", frequency: 22 },
  { hanzi: "长期", pinyin: "chángqī", english: "long-term; long-period", pos: "adj", frequency: 23 },
  { hanzi: "常识", pinyin: "chángshí", english: "common sense; general knowledge", pos: "n", frequency: 24 },
  { hanzi: "彻底", pinyin: "chèdǐ", english: "thorough; thoroughgoing", pos: "adj/adv", frequency: 25 },
  { hanzi: "趁", pinyin: "chèn", english: "to take advantage of; while", pos: "prep", frequency: 26 },
  { hanzi: "成就", pinyin: "chéngjiù", english: "achievement; accomplishment", pos: "n", frequency: 27 },
  { hanzi: "成熟", pinyin: "chéngshú", english: "mature; ripe", pos: "adj", frequency: 28 },
  { hanzi: "承担", pinyin: "chéngdān", english: "to undertake; to bear (responsibility)", pos: "v", frequency: 29 },
  { hanzi: "承认", pinyin: "chéngrèn", english: "to admit; to acknowledge; to recognize", pos: "v", frequency: 30 },
  { hanzi: "充分", pinyin: "chōngfèn", english: "ample; sufficient; fully", pos: "adj/adv", frequency: 31 },
  { hanzi: "重视", pinyin: "zhòngshì", english: "to attach importance to; to value", pos: "v", frequency: 32 },
  { hanzi: "出口", pinyin: "chūkǒu", english: "exit; to export", pos: "n/v", frequency: 33 },
  { hanzi: "出色", pinyin: "chūsè", english: "outstanding; excellent", pos: "adj", frequency: 34 },
  { hanzi: "处理", pinyin: "chǔlǐ", english: "to handle; to deal with; to process", pos: "v", frequency: 35 },
  { hanzi: "此外", pinyin: "cǐwài", english: "besides; in addition; moreover", pos: "conj", frequency: 36 },
  { hanzi: "促进", pinyin: "cùjìn", english: "to promote; to advance", pos: "v", frequency: 37 },
  { hanzi: "存在", pinyin: "cúnzài", english: "to exist; existence", pos: "v/n", frequency: 38 },
  { hanzi: "措施", pinyin: "cuòshī", english: "measure; step (action taken)", pos: "n", frequency: 39 },
  { hanzi: "达到", pinyin: "dádào", english: "to reach; to achieve; to attain", pos: "v", frequency: 40 },
  { hanzi: "大量", pinyin: "dàliàng", english: "a large number of; a great deal of", pos: "adj", frequency: 41 },
  { hanzi: "担任", pinyin: "dānrèn", english: "to serve as; to hold the position of", pos: "v", frequency: 42 },
  { hanzi: "当地", pinyin: "dāngdì", english: "local; locally", pos: "adj/n", frequency: 43 },
  { hanzi: "导致", pinyin: "dǎozhì", english: "to lead to; to cause; to result in", pos: "v", frequency: 44 },
  { hanzi: "道理", pinyin: "dàoli", english: "reason; principle; sense", pos: "n", frequency: 45 },
  { hanzi: "等于", pinyin: "děngyú", english: "to equal; to be equivalent to", pos: "v", frequency: 46 },
  { hanzi: "地位", pinyin: "dìwèi", english: "status; position; standing", pos: "n", frequency: 47 },
  { hanzi: "典型", pinyin: "diǎnxíng", english: "typical; representative; classic case", pos: "adj/n", frequency: 48 },
  { hanzi: "对象", pinyin: "duìxiàng", english: "target; object; partner", pos: "n", frequency: 49 },
  { hanzi: "多余", pinyin: "duōyú", english: "superfluous; surplus; redundant", pos: "adj", frequency: 50 },
  { hanzi: "耳环", pinyin: "ěrhuán", english: "earring", pos: "n", frequency: 51 },
  { hanzi: "发挥", pinyin: "fāhuī", english: "to give play to; to bring into full play", pos: "v", frequency: 52 },
  { hanzi: "繁荣", pinyin: "fánróng", english: "prosperous; booming; flourishing", pos: "adj", frequency: 53 },
  { hanzi: "反对", pinyin: "fǎnduì", english: "to oppose; to be against", pos: "v", frequency: 54 },
  { hanzi: "范围", pinyin: "fànwéi", english: "range; scope; extent", pos: "n", frequency: 55 },
  { hanzi: "方案", pinyin: "fāng'àn", english: "plan; scheme; proposal", pos: "n", frequency: 56 },
  { hanzi: "否认", pinyin: "fǒurèn", english: "to deny; to repudiate", pos: "v", frequency: 57 },
  { hanzi: "服从", pinyin: "fúcóng", english: "to obey; to comply with", pos: "v", frequency: 58 },
  { hanzi: "付出", pinyin: "fùchū", english: "to pay; to put in (effort)", pos: "v", frequency: 59 },
  { hanzi: "改变", pinyin: "gǎibiàn", english: "to change; to alter", pos: "v", frequency: 60 },
  { hanzi: "改革", pinyin: "gǎigé", english: "to reform; reform", pos: "v/n", frequency: 61 },
  { hanzi: "干脆", pinyin: "gāncuì", english: "straightforward; simply; just", pos: "adj/adv", frequency: 62 },
  { hanzi: "高级", pinyin: "gāojí", english: "advanced; high-level; senior", pos: "adj", frequency: 63 },
  { hanzi: "个别", pinyin: "gèbié", english: "individual; separate; exceptional", pos: "adj", frequency: 64 },
  { hanzi: "工资", pinyin: "gōngzī", english: "wages; salary", pos: "n", frequency: 65 },
  { hanzi: "构成", pinyin: "gòuchéng", english: "to constitute; to form; to compose", pos: "v", frequency: 66 },
  { hanzi: "鼓励", pinyin: "gǔlì", english: "to encourage; encouragement", pos: "v/n", frequency: 67 },
  { hanzi: "鼓掌", pinyin: "gǔzhǎng", english: "to applaud; to clap", pos: "v", frequency: 68 },
  { hanzi: "固然", pinyin: "gùrán", english: "admittedly; of course; it is true", pos: "adv/conj", frequency: 69 },
  { hanzi: "关键", pinyin: "guānjiàn", english: "key; crucial; critical", pos: "n/adj", frequency: 70 },
  { hanzi: "广大", pinyin: "guǎngdà", english: "vast; wide; numerous", pos: "adj", frequency: 71 },
  { hanzi: "规律", pinyin: "guīlǜ", english: "law; rule; pattern", pos: "n", frequency: 72 },
  { hanzi: "后果", pinyin: "hòuguǒ", english: "consequence; aftermath", pos: "n", frequency: 73 },
  { hanzi: "忽视", pinyin: "hūshì", english: "to ignore; to neglect; to overlook", pos: "v", frequency: 74 },
  { hanzi: "基本", pinyin: "jīběn", english: "basic; fundamental; mainly", pos: "adj/adv", frequency: 75 },
  { hanzi: "激动", pinyin: "jīdòng", english: "excited; to excite; moved", pos: "adj/v", frequency: 76 },
  { hanzi: "及时", pinyin: "jíshí", english: "timely; prompt; in time", pos: "adj/adv", frequency: 77 },
  { hanzi: "集中", pinyin: "jízhōng", english: "to concentrate; centralized; to focus", pos: "v/adj", frequency: 78 },
  { hanzi: "寂寞", pinyin: "jìmò", english: "lonely; lonesome", pos: "adj", frequency: 79 },
  { hanzi: "加以", pinyin: "jiāyǐ", english: "to handle; to deal with (formal)", pos: "v", frequency: 80 },
  { hanzi: "假设", pinyin: "jiǎshè", english: "to assume; hypothesis; if", pos: "v/n/conj", frequency: 81 },
  { hanzi: "坚强", pinyin: "jiānqiáng", english: "strong; firm; determined", pos: "adj", frequency: 82 },
  { hanzi: "减少", pinyin: "jiǎnshǎo", english: "to reduce; to decrease", pos: "v", frequency: 83 },
  { hanzi: "健全", pinyin: "jiànquán", english: "sound; perfect; to improve", pos: "adj/v", frequency: 84 },
  { hanzi: "结合", pinyin: "jiéhé", english: "to combine; to integrate; combination", pos: "v/n", frequency: 85 },
  { hanzi: "金融", pinyin: "jīnróng", english: "finance; financial", pos: "n/adj", frequency: 86 },
  { hanzi: "尽力", pinyin: "jìnlì", english: "to do one's best; to try one's utmost", pos: "v", frequency: 87 },
  { hanzi: "竞争", pinyin: "jìngzhēng", english: "to compete; competition", pos: "v/n", frequency: 88 },
  { hanzi: "纠纷", pinyin: "jiūfēn", english: "dispute; conflict", pos: "n", frequency: 89 },
  { hanzi: "举例", pinyin: "jǔlì", english: "to give an example; for example", pos: "v", frequency: 90 },
  { hanzi: "具备", pinyin: "jùbèi", english: "to possess; to have; to be equipped with", pos: "v", frequency: 91 },
  { hanzi: "具体", pinyin: "jùtǐ", english: "concrete; specific; definite", pos: "adj", frequency: 92 },
  { hanzi: "开发", pinyin: "kāifā", english: "to develop; to exploit; to open up", pos: "v", frequency: 93 },
  { hanzi: "客观", pinyin: "kèguān", english: "objective; unbiased", pos: "adj", frequency: 94 },
  { hanzi: "控制", pinyin: "kòngzhì", english: "to control; to manage; control", pos: "v/n", frequency: 95 },
  { hanzi: "扩大", pinyin: "kuòdà", english: "to expand; to enlarge", pos: "v", frequency: 96 },
  { hanzi: "来源", pinyin: "láiyuán", english: "source; origin", pos: "n", frequency: 97 },
  { hanzi: "理论", pinyin: "lǐlùn", english: "theory; theoretical", pos: "n/adj", frequency: 98 },
  { hanzi: "立即", pinyin: "lìjí", english: "immediately; at once", pos: "adv", frequency: 99 },
  { hanzi: "利益", pinyin: "lìyì", english: "interest; benefit; profit", pos: "n", frequency: 100 },
  { hanzi: "力量", pinyin: "lìliàng", english: "strength; power; force", pos: "n", frequency: 101 },
  { hanzi: "逐渐", pinyin: "zhújiàn", english: "gradually; by degrees", pos: "adv", frequency: 102 },
  { hanzi: "主动", pinyin: "zhǔdòng", english: "initiative; active; on one's own", pos: "adj/n", frequency: 103 },
  { hanzi: "主观", pinyin: "zhǔguān", english: "subjective", pos: "adj", frequency: 104 },
  { hanzi: "主张", pinyin: "zhǔzhāng", english: "to advocate; position; view", pos: "v/n", frequency: 105 },
  { hanzi: "专业", pinyin: "zhuānyè", english: "major; specialty; professional", pos: "n/adj", frequency: 106 },
  { hanzi: "转变", pinyin: "zhuǎnbiàn", english: "to transform; to change", pos: "v/n", frequency: 107 },
  { hanzi: "资格", pinyin: "zīgé", english: "qualification; credentials", pos: "n", frequency: 108 },
  { hanzi: "资源", pinyin: "zīyuán", english: "resource; natural resource", pos: "n", frequency: 109 },
  { hanzi: "自从", pinyin: "zìcóng", english: "since; from (a point in time)", pos: "prep", frequency: 110 },
  { hanzi: "自觉", pinyin: "zìjué", english: "conscious; aware; voluntary", pos: "adj", frequency: 111 },
  { hanzi: "自信", pinyin: "zìxìn", english: "self-confident; confidence", pos: "adj/n", frequency: 112 },
  { hanzi: "总结", pinyin: "zǒngjié", english: "to summarize; summary", pos: "v/n", frequency: 113 },
  { hanzi: "总体", pinyin: "zǒngtǐ", english: "overall; general; as a whole", pos: "adj/n", frequency: 114 },
  { hanzi: "作用", pinyin: "zuòyòng", english: "role; function; effect", pos: "n", frequency: 115 },
  { hanzi: "满足", pinyin: "mǎnzú", english: "to satisfy; satisfied; content", pos: "v/adj", frequency: 116 },
  { hanzi: "矛盾", pinyin: "máodùn", english: "contradiction; conflict; contradictory", pos: "n/adj", frequency: 117 },
  { hanzi: "冒险", pinyin: "màoxiǎn", english: "to take risks; adventure", pos: "v/n", frequency: 118 },
  { hanzi: "描写", pinyin: "miáoxiě", english: "to describe; description; portrayal", pos: "v/n", frequency: 119 },
  { hanzi: "明确", pinyin: "míngquè", english: "clear; definite; to clarify", pos: "adj/v", frequency: 120 },
  { hanzi: "目标", pinyin: "mùbiāo", english: "goal; target; objective", pos: "n", frequency: 121 },
  { hanzi: "内心", pinyin: "nèixīn", english: "inner; innermost heart", pos: "n", frequency: 122 },
  { hanzi: "年代", pinyin: "niándài", english: "era; decade; years", pos: "n", frequency: 123 },
  { hanzi: "凭", pinyin: "píng", english: "to rely on; based on; by means of", pos: "prep/v", frequency: 124 },
  { hanzi: "气氛", pinyin: "qìfēn", english: "atmosphere; ambiance", pos: "n", frequency: 125 },
  { hanzi: "前途", pinyin: "qiántú", english: "future; prospects", pos: "n", frequency: 126 },
  { hanzi: "缺乏", pinyin: "quēfá", english: "to lack; shortage", pos: "v/n", frequency: 127 },
  { hanzi: "热烈", pinyin: "rèliè", english: "warm; enthusiastic; fervent", pos: "adj", frequency: 128 },
  { hanzi: "人才", pinyin: "réncái", english: "talent; talented person", pos: "n", frequency: 129 },
  { hanzi: "人物", pinyin: "rénwù", english: "figure; character; personage", pos: "n", frequency: 130 },
  { hanzi: "认真", pinyin: "rènzhēn", english: "serious; earnest; conscientious", pos: "adj", frequency: 131 },
  { hanzi: "日益", pinyin: "rìyì", english: "increasingly; day by day", pos: "adv", frequency: 132 },
  { hanzi: "软件", pinyin: "ruǎnjiàn", english: "software", pos: "n", frequency: 133 },
  { hanzi: "手段", pinyin: "shǒuduàn", english: "method; means; measure", pos: "n", frequency: 134 },
  { hanzi: "实际", pinyin: "shíjì", english: "actual; practical; in practice", pos: "adj/n", frequency: 135 },
  { hanzi: "实现", pinyin: "shíxiàn", english: "to realize; to achieve; to accomplish", pos: "v", frequency: 136 },
  { hanzi: "事实", pinyin: "shìshí", english: "fact; reality", pos: "n", frequency: 137 },
  { hanzi: "收获", pinyin: "shōuhuò", english: "to harvest; gain; result", pos: "v/n", frequency: 138 },
  { hanzi: "双方", pinyin: "shuāngfāng", english: "both parties; both sides", pos: "n", frequency: 139 },
  { hanzi: "思想", pinyin: "sīxiǎng", english: "thought; thinking; ideology", pos: "n", frequency: 140 },
  { hanzi: "讨论", pinyin: "tǎolùn", english: "to discuss; discussion", pos: "v/n", frequency: 141 },
  { hanzi: "提高", pinyin: "tígāo", english: "to raise; to improve; to enhance", pos: "v", frequency: 142 },
  { hanzi: "体会", pinyin: "tǐhuì", english: "to realize; to appreciate; experience", pos: "v/n", frequency: 143 },
  { hanzi: "推动", pinyin: "tuīdòng", english: "to push forward; to promote", pos: "v", frequency: 144 },
  { hanzi: "完善", pinyin: "wánshàn", english: "to perfect; to improve; perfect", pos: "v/adj", frequency: 145 },
  { hanzi: "维护", pinyin: "wéihù", english: "to safeguard; to maintain; to protect", pos: "v", frequency: 146 },
  { hanzi: "文明", pinyin: "wénmíng", english: "civilization; civilized", pos: "n/adj", frequency: 147 },
  { hanzi: "稳定", pinyin: "wěndìng", english: "stable; to stabilize", pos: "adj/v", frequency: 148 },
  { hanzi: "物质", pinyin: "wùzhì", english: "material; substance; physical", pos: "n/adj", frequency: 149 },
  { hanzi: "系统", pinyin: "xìtǒng", english: "system; systematic", pos: "n/adj", frequency: 150 },
];
