import type { RawWord } from "../parse-hsk-data";

export const hsk6Words: RawWord[] = [
  { hanzi: "哀悼", pinyin: "āidào", english: "to mourn; to grieve", pos: "v", frequency: 1 },
  { hanzi: "爱戴", pinyin: "àidài", english: "to love and respect; to hold in esteem", pos: "v", frequency: 2 },
  { hanzi: "安慰", pinyin: "ānwèi", english: "to comfort; consolation", pos: "v/n", frequency: 3 },
  { hanzi: "安装", pinyin: "ānzhuāng", english: "to install; to set up", pos: "v", frequency: 4 },
  { hanzi: "把握", pinyin: "bǎwò", english: "certainty; to grasp", pos: "n/v", frequency: 5 },
  { hanzi: "颁布", pinyin: "bānbù", english: "to promulgate; to issue (law/decree)", pos: "v", frequency: 6 },
  { hanzi: "包含", pinyin: "bāohán", english: "to contain; to include", pos: "v", frequency: 7 },
  { hanzi: "保存", pinyin: "bǎocún", english: "to preserve; to keep; to save", pos: "v", frequency: 8 },
  { hanzi: "报复", pinyin: "bàofù", english: "to retaliate; revenge", pos: "v/n", frequency: 9 },
  { hanzi: "悲剧", pinyin: "bēijù", english: "tragedy; tragic", pos: "n/adj", frequency: 10 },
  { hanzi: "本能", pinyin: "běnnéng", english: "instinct; instinctive", pos: "n/adj", frequency: 11 },
  { hanzi: "比例", pinyin: "bǐlì", english: "proportion; ratio", pos: "n", frequency: 12 },
  { hanzi: "必要", pinyin: "bìyào", english: "necessary; essential; necessity", pos: "adj/n", frequency: 13 },
  { hanzi: "编辑", pinyin: "biānjí", english: "to edit; editor", pos: "v/n", frequency: 14 },
  { hanzi: "辩论", pinyin: "biànlùn", english: "to debate; debate", pos: "v/n", frequency: 15 },
  { hanzi: "标志", pinyin: "biāozhì", english: "symbol; sign; to mark", pos: "n/v", frequency: 16 },
  { hanzi: "并非", pinyin: "bìngfēi", english: "not at all; by no means", pos: "adv", frequency: 17 },
  { hanzi: "博大", pinyin: "bódà", english: "broad; extensive; vast", pos: "adj", frequency: 18 },
  { hanzi: "补充", pinyin: "bǔchōng", english: "to supplement; to add; supplement", pos: "v/n", frequency: 19 },
  { hanzi: "不得已", pinyin: "bùdéyǐ", english: "have no choice but; compelled", pos: "adv", frequency: 20 },
  { hanzi: "不足", pinyin: "bùzú", english: "insufficient; inadequate; not enough", pos: "adj/n", frequency: 21 },
  { hanzi: "采用", pinyin: "cǎiyòng", english: "to adopt; to employ; to use", pos: "v", frequency: 22 },
  { hanzi: "参与", pinyin: "cānyù", english: "to participate; to be involved in", pos: "v", frequency: 23 },
  { hanzi: "惭愧", pinyin: "cánkuì", english: "ashamed; abashed", pos: "adj", frequency: 24 },
  { hanzi: "策略", pinyin: "cèlüè", english: "strategy; tactic", pos: "n", frequency: 25 },
  { hanzi: "阐述", pinyin: "chǎnshù", english: "to elaborate; to expound", pos: "v", frequency: 26 },
  { hanzi: "沉默", pinyin: "chénmò", english: "silent; silence; to keep silent", pos: "adj/n/v", frequency: 27 },
  { hanzi: "成分", pinyin: "chéngfèn", english: "ingredient; component; element", pos: "n", frequency: 28 },
  { hanzi: "充实", pinyin: "chōngshí", english: "rich; substantial; to enrich", pos: "adj/v", frequency: 29 },
  { hanzi: "抽象", pinyin: "chōuxiàng", english: "abstract", pos: "adj", frequency: 30 },
  { hanzi: "出路", pinyin: "chūlù", english: "way out; outlet; prospect", pos: "n", frequency: 31 },
  { hanzi: "创造", pinyin: "chuàngzào", english: "to create; to produce; creation", pos: "v/n", frequency: 32 },
  { hanzi: "创新", pinyin: "chuàngxīn", english: "innovation; to innovate", pos: "n/v", frequency: 33 },
  { hanzi: "纯粹", pinyin: "chúncuì", english: "pure; purely; simply", pos: "adj/adv", frequency: 34 },
  { hanzi: "从而", pinyin: "cóng'ér", english: "thus; thereby; as a result", pos: "conj", frequency: 35 },
  { hanzi: "从事", pinyin: "cóngshì", english: "to be engaged in; to work in", pos: "v", frequency: 36 },
  { hanzi: "粗糙", pinyin: "cūcāo", english: "rough; coarse; crude", pos: "adj", frequency: 37 },
  { hanzi: "催促", pinyin: "cuīcù", english: "to urge; to hasten; to press", pos: "v", frequency: 38 },
  { hanzi: "大幅度", pinyin: "dà fúdù", english: "by a large margin; substantially", pos: "adv", frequency: 39 },
  { hanzi: "带动", pinyin: "dàidòng", english: "to drive; to lead; to bring along", pos: "v", frequency: 40 },
  { hanzi: "当代", pinyin: "dāngdài", english: "contemporary; present-day", pos: "n/adj", frequency: 41 },
  { hanzi: "当初", pinyin: "dāngchū", english: "at the beginning; originally; at that time", pos: "n", frequency: 42 },
  { hanzi: "道德", pinyin: "dàodé", english: "morality; moral; ethics", pos: "n/adj", frequency: 43 },
  { hanzi: "的确", pinyin: "díquè", english: "indeed; really; certainly", pos: "adv", frequency: 44 },
  { hanzi: "抵制", pinyin: "dǐzhì", english: "to resist; to boycott", pos: "v", frequency: 45 },
  { hanzi: "典礼", pinyin: "diǎnlǐ", english: "ceremony; celebration", pos: "n", frequency: 46 },
  { hanzi: "动机", pinyin: "dòngjī", english: "motive; motivation", pos: "n", frequency: 47 },
  { hanzi: "独立", pinyin: "dúlì", english: "independent; independence; to be independent", pos: "adj/n/v", frequency: 48 },
  { hanzi: "段落", pinyin: "duànluò", english: "paragraph; section", pos: "n", frequency: 49 },
  { hanzi: "对比", pinyin: "duìbǐ", english: "contrast; to contrast; to compare", pos: "n/v", frequency: 50 },
  { hanzi: "对待", pinyin: "duìdài", english: "to treat; to handle; to deal with", pos: "v", frequency: 51 },
  { hanzi: "多元化", pinyin: "duōyuánhuà", english: "diversification; pluralistic", pos: "n/adj", frequency: 52 },
  { hanzi: "发言", pinyin: "fāyán", english: "to speak; to address; statement", pos: "v/n", frequency: 53 },
  { hanzi: "翻译", pinyin: "fānyì", english: "to translate; translator; translation", pos: "v/n", frequency: 54 },
  { hanzi: "反映", pinyin: "fǎnyìng", english: "to reflect; to mirror; to report", pos: "v", frequency: 55 },
  { hanzi: "方式", pinyin: "fāngshì", english: "way; manner; mode", pos: "n", frequency: 56 },
  { hanzi: "丰富", pinyin: "fēngfù", english: "rich; abundant; to enrich", pos: "adj/v", frequency: 57 },
  { hanzi: "风格", pinyin: "fēnggé", english: "style; manner", pos: "n", frequency: 58 },
  { hanzi: "伏", pinyin: "fú", english: "to bend over; to lie prostrate; ambush", pos: "v/n", frequency: 59 },
  { hanzi: "服务", pinyin: "fúwù", english: "service; to serve", pos: "n/v", frequency: 60 },
  { hanzi: "根本", pinyin: "gēnběn", english: "fundamental; basic; at all; simply", pos: "adj/adv", frequency: 61 },
  { hanzi: "功能", pinyin: "gōngnéng", english: "function; capability", pos: "n", frequency: 62 },
  { hanzi: "攻击", pinyin: "gōngjī", english: "to attack; to assault; attack", pos: "v/n", frequency: 63 },
  { hanzi: "贡献", pinyin: "gòngxiàn", english: "contribution; to contribute", pos: "n/v", frequency: 64 },
  { hanzi: "孤独", pinyin: "gūdú", english: "lonely; solitary; loneliness", pos: "adj/n", frequency: 65 },
  { hanzi: "固定", pinyin: "gùdìng", english: "fixed; regular; to fix", pos: "adj/v", frequency: 66 },
  { hanzi: "过渡", pinyin: "guòdù", english: "transition; to transition", pos: "n/v", frequency: 67 },
  { hanzi: "海拔", pinyin: "hǎibá", english: "altitude above sea level; elevation", pos: "n", frequency: 68 },
  { hanzi: "豪华", pinyin: "háohuá", english: "luxurious; extravagant", pos: "adj", frequency: 69 },
  { hanzi: "合理", pinyin: "hélǐ", english: "reasonable; rational", pos: "adj", frequency: 70 },
  { hanzi: "核心", pinyin: "héxīn", english: "core; nucleus; central", pos: "n/adj", frequency: 71 },
  { hanzi: "宏观", pinyin: "hóngguān", english: "macro; macroscopic", pos: "adj", frequency: 72 },
  { hanzi: "华丽", pinyin: "huálì", english: "gorgeous; magnificent; splendid", pos: "adj", frequency: 73 },
  { hanzi: "混合", pinyin: "hùnhé", english: "to mix; to blend; mixture", pos: "v/n", frequency: 74 },
  { hanzi: "机制", pinyin: "jīzhì", english: "mechanism; system", pos: "n", frequency: 75 },
  { hanzi: "极端", pinyin: "jíduān", english: "extreme; extremity", pos: "adj/n", frequency: 76 },
  { hanzi: "即便", pinyin: "jíbiàn", english: "even if; even though", pos: "conj", frequency: 77 },
  { hanzi: "激励", pinyin: "jīlì", english: "to inspire; to motivate; incentive", pos: "v/n", frequency: 78 },
  { hanzi: "加强", pinyin: "jiāqiáng", english: "to strengthen; to enhance", pos: "v", frequency: 79 },
  { hanzi: "坚决", pinyin: "jiānjué", english: "resolute; determined; firmly", pos: "adj/adv", frequency: 80 },
  { hanzi: "坚韧", pinyin: "jiānrèn", english: "tenacious; tough and resilient", pos: "adj", frequency: 81 },
  { hanzi: "监督", pinyin: "jiāndū", english: "to supervise; to oversee; supervision", pos: "v/n", frequency: 82 },
  { hanzi: "揭示", pinyin: "jiēshì", english: "to reveal; to expose; to display", pos: "v", frequency: 83 },
  { hanzi: "精华", pinyin: "jīnghuá", english: "essence; the best part; quintessence", pos: "n", frequency: 84 },
  { hanzi: "精确", pinyin: "jīngquè", english: "precise; accurate; exact", pos: "adj", frequency: 85 },
  { hanzi: "局部", pinyin: "júbù", english: "part; local; partial", pos: "n/adj", frequency: 86 },
  { hanzi: "均匀", pinyin: "jūnyún", english: "even; uniform; well-distributed", pos: "adj", frequency: 87 },
  { hanzi: "开展", pinyin: "kāizhǎn", english: "to launch; to carry out; to develop", pos: "v", frequency: 88 },
  { hanzi: "抗议", pinyin: "kàngyì", english: "to protest; protest", pos: "v/n", frequency: 89 },
  { hanzi: "可见", pinyin: "kějiàn", english: "it can be seen; obviously", pos: "conj", frequency: 90 },
  { hanzi: "克服", pinyin: "kèfú", english: "to overcome; to surmount", pos: "v", frequency: 91 },
  { hanzi: "客观", pinyin: "kèguān", english: "objective; unbiased", pos: "adj", frequency: 92 },
  { hanzi: "空洞", pinyin: "kōngdòng", english: "hollow; empty; void", pos: "adj/n", frequency: 93 },
  { hanzi: "框架", pinyin: "kuàngjià", english: "framework; structure", pos: "n", frequency: 94 },
  { hanzi: "扩展", pinyin: "kuòzhǎn", english: "to expand; to extend; expansion", pos: "v/n", frequency: 95 },
  { hanzi: "浪潮", pinyin: "làngcháo", english: "wave; tide (figurative)", pos: "n", frequency: 96 },
  { hanzi: "类别", pinyin: "lèibié", english: "category; classification; type", pos: "n", frequency: 97 },
  { hanzi: "理念", pinyin: "lǐniàn", english: "idea; philosophy; concept", pos: "n", frequency: 98 },
  { hanzi: "立场", pinyin: "lìchǎng", english: "standpoint; position; stance", pos: "n", frequency: 99 },
  { hanzi: "联合", pinyin: "liánhé", english: "to unite; joint; combined", pos: "v/adj", frequency: 100 },
  { hanzi: "灵活", pinyin: "línghuó", english: "flexible; agile; nimble", pos: "adj", frequency: 101 },
  { hanzi: "逻辑", pinyin: "luójí", english: "logic; logical", pos: "n/adj", frequency: 102 },
  { hanzi: "模式", pinyin: "móshì", english: "mode; model; pattern", pos: "n", frequency: 103 },
  { hanzi: "难以", pinyin: "nányǐ", english: "difficult to; hard to", pos: "adv", frequency: 104 },
  { hanzi: "内涵", pinyin: "nèihán", english: "connotation; inner meaning", pos: "n", frequency: 105 },
  { hanzi: "凝聚", pinyin: "níngjù", english: "to condense; to gather; to coalesce", pos: "v", frequency: 106 },
  { hanzi: "偶然", pinyin: "ǒurán", english: "accidental; by chance; occasional", pos: "adj/adv", frequency: 107 },
  { hanzi: "批判", pinyin: "pīpàn", english: "to criticize; criticism (ideological)", pos: "v/n", frequency: 108 },
  { hanzi: "品味", pinyin: "pǐnwèi", english: "taste; refinement; to taste", pos: "n/v", frequency: 109 },
  { hanzi: "平衡", pinyin: "pínghéng", english: "balance; equilibrium; to balance", pos: "n/v/adj", frequency: 110 },
  { hanzi: "普遍", pinyin: "pǔbiàn", english: "universal; common; widespread", pos: "adj", frequency: 111 },
  { hanzi: "期望", pinyin: "qīwàng", english: "to expect; expectation; hope", pos: "v/n", frequency: 112 },
  { hanzi: "潜力", pinyin: "qiánlì", english: "potential; latent capability", pos: "n", frequency: 113 },
  { hanzi: "强调", pinyin: "qiángdiào", english: "to emphasize; to stress; emphasis", pos: "v/n", frequency: 114 },
  { hanzi: "强烈", pinyin: "qiángliè", english: "strong; intense; fierce", pos: "adj", frequency: 115 },
  { hanzi: "认可", pinyin: "rènkě", english: "to approve; to accept; approval", pos: "v/n", frequency: 116 },
  { hanzi: "融合", pinyin: "rónghé", english: "to merge; to blend; fusion", pos: "v/n", frequency: 117 },
  { hanzi: "色彩", pinyin: "sècǎi", english: "color; hue; tint", pos: "n", frequency: 118 },
  { hanzi: "设施", pinyin: "shèshī", english: "facilities; installation", pos: "n", frequency: 119 },
  { hanzi: "深刻", pinyin: "shēnkè", english: "profound; deep; deeply", pos: "adj/adv", frequency: 120 },
  { hanzi: "审查", pinyin: "shěnchá", english: "to examine; to review; censorship", pos: "v/n", frequency: 121 },
  { hanzi: "生态", pinyin: "shēngtài", english: "ecology; ecosystem", pos: "n", frequency: 122 },
  { hanzi: "实施", pinyin: "shíshī", english: "to implement; to carry out", pos: "v", frequency: 123 },
  { hanzi: "是非", pinyin: "shìfēi", english: "right and wrong; dispute", pos: "n", frequency: 124 },
  { hanzi: "适应", pinyin: "shìyìng", english: "to adapt; to adjust to", pos: "v", frequency: 125 },
  { hanzi: "束缚", pinyin: "shùfù", english: "to bind; to restrain; constraint", pos: "v/n", frequency: 126 },
  { hanzi: "探索", pinyin: "tànsuǒ", english: "to explore; to probe; exploration", pos: "v/n", frequency: 127 },
  { hanzi: "体现", pinyin: "tǐxiàn", english: "to embody; to reflect; to manifest", pos: "v", frequency: 128 },
  { hanzi: "通过", pinyin: "tōngguò", english: "to pass through; by means of; through", pos: "v/prep", frequency: 129 },
  { hanzi: "同情", pinyin: "tóngqíng", english: "sympathy; to sympathize with", pos: "n/v", frequency: 130 },
  { hanzi: "透明", pinyin: "tòumíng", english: "transparent; open", pos: "adj", frequency: 131 },
  { hanzi: "突出", pinyin: "tūchū", english: "to stand out; outstanding; prominent", pos: "v/adj", frequency: 132 },
  { hanzi: "推广", pinyin: "tuīguǎng", english: "to promote; to spread; to popularize", pos: "v", frequency: 133 },
  { hanzi: "完整", pinyin: "wánzhěng", english: "complete; intact; whole", pos: "adj", frequency: 134 },
  { hanzi: "微观", pinyin: "wēiguān", english: "micro; microscopic", pos: "adj", frequency: 135 },
  { hanzi: "危机", pinyin: "wēijī", english: "crisis", pos: "n", frequency: 136 },
  { hanzi: "相关", pinyin: "xiāngguān", english: "related; relevant; correlated", pos: "adj", frequency: 137 },
  { hanzi: "象征", pinyin: "xiàngzhēng", english: "symbol; to symbolize", pos: "n/v", frequency: 138 },
  { hanzi: "效果", pinyin: "xiàoguǒ", english: "effect; result; effectiveness", pos: "n", frequency: 139 },
  { hanzi: "形成", pinyin: "xíngchéng", english: "to form; to take shape; formation", pos: "v/n", frequency: 140 },
  { hanzi: "形式", pinyin: "xíngshì", english: "form; shape; formality", pos: "n", frequency: 141 },
  { hanzi: "行为", pinyin: "xíngwéi", english: "behavior; conduct; action", pos: "n", frequency: 142 },
  { hanzi: "修改", pinyin: "xiūgǎi", english: "to revise; to modify; to amend", pos: "v", frequency: 143 },
  { hanzi: "虚伪", pinyin: "xūwěi", english: "hypocritical; false; dishonest", pos: "adj", frequency: 144 },
  { hanzi: "延伸", pinyin: "yánshēn", english: "to extend; to stretch; extension", pos: "v/n", frequency: 145 },
  { hanzi: "严格", pinyin: "yángé", english: "strict; rigorous; strictly", pos: "adj/adv", frequency: 146 },
  { hanzi: "要素", pinyin: "yàosù", english: "essential factor; key element", pos: "n", frequency: 147 },
  { hanzi: "依据", pinyin: "yījù", english: "basis; grounds; to be based on", pos: "n/v", frequency: 148 },
  { hanzi: "异常", pinyin: "yìcháng", english: "abnormal; unusual; extremely", pos: "adj/adv", frequency: 149 },
  { hanzi: "意义", pinyin: "yìyì", english: "meaning; significance; sense", pos: "n", frequency: 150 },
  { hanzi: "引发", pinyin: "yǐnfā", english: "to trigger; to cause; to spark", pos: "v", frequency: 151 },
  { hanzi: "引起", pinyin: "yǐnqǐ", english: "to cause; to give rise to; to lead to", pos: "v", frequency: 152 },
  { hanzi: "营养", pinyin: "yíngyǎng", english: "nutrition; nourishment", pos: "n", frequency: 153 },
  { hanzi: "优势", pinyin: "yōushì", english: "advantage; superiority", pos: "n", frequency: 154 },
  { hanzi: "有效", pinyin: "yǒuxiào", english: "effective; valid; efficient", pos: "adj", frequency: 155 },
  { hanzi: "预测", pinyin: "yùcè", english: "to predict; prediction; forecast", pos: "v/n", frequency: 156 },
  { hanzi: "原则", pinyin: "yuánzé", english: "principle; rule", pos: "n", frequency: 157 },
  { hanzi: "整体", pinyin: "zhěngtǐ", english: "whole; overall; entirety", pos: "n/adj", frequency: 158 },
  { hanzi: "支持", pinyin: "zhīchí", english: "to support; support", pos: "v/n", frequency: 159 },
  { hanzi: "执行", pinyin: "zhíxíng", english: "to execute; to carry out; to implement", pos: "v", frequency: 160 },
];
